import type {
  InsurerConfigForm,
  PortalClaim,
  PortalInsurer,
  PortalProduct,
  PortalProposal,
} from "@/lib/types";

export const fallbackInsurers: PortalInsurer[] = [
  {
    id: "fallback-pragati-insurance",
    code: "PRAGATI",
    name: "PRAGATI INSURANCE",
    type: "Non-life",
    status: "Active",
    email: "health@pragatiinsurance.com",
    phone: "+880255012683",
    websiteUrl: "https://www.pragatiinsurance.com",
    businessModel:
      "Dual-entity market coverage, bancassurance, B2B group solutions, financial inclusion, health-tech TPA, and reinsurance-backed non-life distribution",
  },
];

export const fallbackProducts: PortalProduct[] = [
  {
    id: "prod-pragati-pet",
    insurerId: "fallback-pragati-insurance",
    code: "PRAGATI-PET",
    name: "Cat & Dog Insurance",
    category: "Pet",
    status: "Active",
    premiumRangeText: "BDT 1,035 - 3,105",
    coverageRangeText: "BDT 10,000 - 30,000",
    features: ["Accidental injury", "Critical illness", "Vet reimbursement"],
  },
  {
    id: "prod-pragati-nibedita",
    insurerId: "fallback-pragati-insurance",
    code: "PRAGATI-NIBEDITA",
    name: "Nibedita",
    category: "Personal Accident",
    status: "Active",
    premiumRangeText: "Configured via partner agreement",
    coverageRangeText: "Benefit schedule based",
    features: ["Women-focused cover", "Trauma allowance", "Household goods damage"],
  },
  {
    id: "prod-pragati-ppa",
    insurerId: "fallback-pragati-insurance",
    code: "PRAGATI-PPA",
    name: "People's Personal Accident",
    category: "Personal Accident",
    status: "Active",
    premiumRangeText: "BDT 74 yearly",
    coverageRangeText: "BDT 100,000",
    features: ["Accidental death", "Permanent disability", "Simple annual pricing"],
  },
  {
    id: "prod-pragati-sorbojonin",
    insurerId: "fallback-pragati-insurance",
    code: "PRAGATI-SSB",
    name: "Sorbojonin Surokkha Bima",
    category: "Personal Accident",
    status: "Active",
    premiumRangeText: "BDT 115 yearly",
    coverageRangeText: "Up to BDT 200,000",
    features: ["Bangladesh-only cover", "Higher benefit cap", "Disability benefits"],
  },
];

export const fallbackProposals: PortalProposal[] = [
  {
    id: "prop-1",
    proposalNumber: "PID-101-2026",
    customerName: "Nadia Rahman",
    customerId: "cust-101",
    orderId: "ord-501",
    category: "Personal Accident",
    planName: "Nibedita",
    coverageText: "Benefit schedule based",
    premiumText: "Partner-distributed pricing",
    status: "In Review",
    submittedAt: "2026-03-14T10:30:00Z",
    decisionReason: "",
    source: "fallback",
  },
  {
    id: "prop-2",
    proposalNumber: "PID-118-2026",
    customerName: "Shafiqul Alam",
    customerId: "cust-102",
    orderId: "ord-502",
    category: "Pet",
    planName: "Cat & Dog Insurance",
    coverageText: "BDT 20,000",
    premiumText: "BDT 2,070",
    status: "Approved",
    submittedAt: "2026-03-11T08:20:00Z",
    decisionReason: "Vaccination record and vet history verified.",
    source: "fallback",
  },
  {
    id: "prop-3",
    proposalNumber: "PID-126-2026",
    customerName: "Abdul Karim",
    customerId: "cust-103",
    orderId: "ord-503",
    category: "Personal Accident",
    planName: "Sorbojonin Surokkha Bima",
    coverageText: "BDT 200,000",
    premiumText: "BDT 115",
    status: "Rejected",
    submittedAt: "2026-03-09T12:15:00Z",
    decisionReason: "Citizenship proof was not provided in the submitted document set.",
    source: "fallback",
  },
];

export const fallbackClaims: PortalClaim[] = [
  {
    id: "claim-1",
    claimNumber: "CLM-2026-PRG-000311",
    insuredName: "Jannatul Ferdous",
    customerId: "cust-101",
    category: "Personal Accident",
    planName: "People's Personal Accident",
    claimedAmountText: "BDT 100,000",
    approvedAmountText: "BDT 100,000",
    settledAmountText: "BDT 0",
    status: "Approved",
    submittedAt: "2026-03-12T09:00:00Z",
    incidentDate: "2026-03-07T00:00:00Z",
    reason: "Accidental disability claim under annual personal accident cover",
    source: "fallback",
  },
  {
    id: "claim-2",
    claimNumber: "CLM-2026-PRG-000427",
    insuredName: "Arif Hossain",
    customerId: "cust-104",
    category: "Pet",
    planName: "Cat & Dog Insurance",
    claimedAmountText: "BDT 18,500",
    approvedAmountText: "BDT 0",
    settledAmountText: "BDT 0",
    status: "Pending Documents",
    submittedAt: "2026-03-13T13:00:00Z",
    incidentDate: "2026-03-10T00:00:00Z",
    reason: "Vet hospitalization claim missing final diagnostic report",
    source: "fallback",
  },
  {
    id: "claim-3",
    claimNumber: "CLM-2026-PRG-000459",
    insuredName: "Farzana Akter",
    customerId: "cust-105",
    category: "Personal Accident",
    planName: "Nibedita",
    claimedAmountText: "BDT 50,000",
    approvedAmountText: "BDT 50,000",
    settledAmountText: "BDT 50,000",
    status: "Settled",
    submittedAt: "2026-03-10T16:00:00Z",
    incidentDate: "2026-03-05T00:00:00Z",
    reason: "Approved trauma allowance disbursement",
    source: "fallback",
  },
];

export const fallbackConfig: InsurerConfigForm = {
  insurerId: "fallback-pragati-insurance",
  apiBaseUrl: "https://partners.labaidinsuretech.com/insurer-api",
  authType: "AUTH_TYPE_BEARER",
  authCredentials: "Configured in gateway secret store",
  businessModel:
    "Dual-entity market coverage, bancassurance, B2B group solutions, financial inclusion, health-tech TPA, and reinsurance-backed non-life distribution",
  autoUnderwritingEnabled: false,
  realTimeClaimNotification: true,
  paymentTerms: "Net 15",
  claimSettlementDays: 10,
};
