package models

// CalculationStatus represents a calculation_status
type CalculationStatus string

// CalculationStatus values
const (
	CalculationStatusCALCULATIONSTATUSUNSPECIFIED CalculationStatus = "CALCULATION_STATUS_UNSPECIFIED"
	CalculationStatusCALCULATIONSTATUSPENDING  = "CALCULATION_STATUS_PENDING"
	CalculationStatusCALCULATIONSTATUSCALCULATING  = "CALCULATION_STATUS_CALCULATING"
	CalculationStatusCALCULATIONSTATUSCOMPLETED  = "CALCULATION_STATUS_COMPLETED"
	CalculationStatusCALCULATIONSTATUSFAILED  = "CALCULATION_STATUS_FAILED"
	CalculationStatusCALCULATIONSTATUSVALIDATED  = "CALCULATION_STATUS_VALIDATED"
)
