package models

// FormulaCategory represents a formula_category
type FormulaCategory string

// FormulaCategory values
const (
	FormulaCategoryFORMULACATEGORYUNSPECIFIED FormulaCategory = "FORMULA_CATEGORY_UNSPECIFIED"
	FormulaCategoryFORMULACATEGORYBASERATE  = "FORMULA_CATEGORY_BASE_RATE"
	FormulaCategoryFORMULACATEGORYRATINGFACTOR  = "FORMULA_CATEGORY_RATING_FACTOR"
	FormulaCategoryFORMULACATEGORYLOADING  = "FORMULA_CATEGORY_LOADING"
	FormulaCategoryFORMULACATEGORYDISCOUNT  = "FORMULA_CATEGORY_DISCOUNT"
	FormulaCategoryFORMULACATEGORYRESERVE  = "FORMULA_CATEGORY_RESERVE"
	FormulaCategoryFORMULACATEGORYLOSSRATIO  = "FORMULA_CATEGORY_LOSS_RATIO"
	FormulaCategoryFORMULACATEGORYEXPENSE  = "FORMULA_CATEGORY_EXPENSE"
	FormulaCategoryFORMULACATEGORYPROFIT  = "FORMULA_CATEGORY_PROFIT"
)
