package models

// InvoiceStatus represents a invoice_status
type InvoiceStatus string

// InvoiceStatus values
const (
	InvoiceStatusINVOICESTATUSUNSPECIFIED InvoiceStatus = "INVOICE_STATUS_UNSPECIFIED"
	InvoiceStatusINVOICESTATUSDRAFT  = "INVOICE_STATUS_DRAFT"
	InvoiceStatusINVOICESTATUSISSUED  = "INVOICE_STATUS_ISSUED"
	InvoiceStatusINVOICESTATUSPENDING  = "INVOICE_STATUS_PENDING"
	InvoiceStatusINVOICESTATUSAPPROVED  = "INVOICE_STATUS_APPROVED"
	InvoiceStatusINVOICESTATUSPAID  = "INVOICE_STATUS_PAID"
	InvoiceStatusINVOICESTATUSOVERDUE  = "INVOICE_STATUS_OVERDUE"
	InvoiceStatusINVOICESTATUSCANCELLED  = "INVOICE_STATUS_CANCELLED"
	InvoiceStatusINVOICESTATUSCREDITNOTEISSUED  = "INVOICE_STATUS_CREDIT_NOTE_ISSUED"
)
