package models

// IoTDeviceType represents a iot_device_type
type IoTDeviceType string

// IoTDeviceType values
const (
	IoTDeviceTypeDEVICETYPEUNSPECIFIED IoTDeviceType = "DEVICE_TYPE_UNSPECIFIED"
	IoTDeviceTypeDEVICETYPEVEHICLETRACKER  = "DEVICE_TYPE_VEHICLE_TRACKER"
	IoTDeviceTypeDEVICETYPEHEALTHMONITOR  = "DEVICE_TYPE_HEALTH_MONITOR"
	IoTDeviceTypeDEVICETYPEHOMESENSOR  = "DEVICE_TYPE_HOME_SENSOR"
	IoTDeviceTypeDEVICETYPEAGRICULTURALSENSOR  = "DEVICE_TYPE_AGRICULTURAL_SENSOR"
)
