package models

// LeadStatus represents a lead_status
type LeadStatus string

// LeadStatus values
const (
	LeadStatusLEADSTATUSUNSPECIFIED LeadStatus = "LEAD_STATUS_UNSPECIFIED"
	LeadStatusLEADSTATUSNEW  = "LEAD_STATUS_NEW"
	LeadStatusLEADSTATUSCONTACTED  = "LEAD_STATUS_CONTACTED"
	LeadStatusLEADSTATUSQUALIFIED  = "LEAD_STATUS_QUALIFIED"
	LeadStatusLEADSOURCEPROPOSAL  = "LEAD_SOURCE_PROPOSAL"
	LeadStatusLEADSTATUSNEGOTIATION  = "LEAD_STATUS_NEGOTIATION"
	LeadStatusLEADSTATUSCONVERTED  = "LEAD_STATUS_CONVERTED"
	LeadStatusLEADSTATUSLOST  = "LEAD_STATUS_LOST"
	LeadStatusLEADSTATUSONHOLD  = "LEAD_STATUS_ON_HOLD"
)
