package models

// LeadSource represents a lead_source
type LeadSource string

// LeadSource values
const (
	LeadSourceLEADSOURCEUNSPECIFIED LeadSource = "LEAD_SOURCE_UNSPECIFIED"
	LeadSourceLEADSOURCEWEBSITE  = "LEAD_SOURCE_WEBSITE"
	LeadSourceLEADSOURCEREFERRAL  = "LEAD_SOURCE_REFERRAL"
	LeadSourceLEADSOURCESOCIALMEDIA  = "LEAD_SOURCE_SOCIAL_MEDIA"
	LeadSourceLEADSOURCEEMAILCAMPAIGN  = "LEAD_SOURCE_EMAIL_CAMPAIGN"
	LeadSourceLEADSOURCEPHONEINQUIRY  = "LEAD_SOURCE_PHONE_INQUIRY"
	LeadSourceLEADSOURCEWALKIN  = "LEAD_SOURCE_WALK_IN"
	LeadSourceLEADSOURCEPARTNER  = "LEAD_SOURCE_PARTNER"
	LeadSourceLEADSOURCEADVERTISEMENT  = "LEAD_SOURCE_ADVERTISEMENT"
	LeadSourceLEADSOURCEEVENT  = "LEAD_SOURCE_EVENT"
	LeadSourceLEADSOURCEOTHER  = "LEAD_SOURCE_OTHER"
)
