package models

// LifeProductType represents a life_product_type
type LifeProductType string

// LifeProductType values
const (
	LifeProductTypeLIFEPRODUCTTYPEUNSPECIFIED LifeProductType = "LIFE_PRODUCT_TYPE_UNSPECIFIED"
	LifeProductTypeLIFEPRODUCTTYPETERM  = "LIFE_PRODUCT_TYPE_TERM"
	LifeProductTypeLIFEPRODUCTTYPEWHOLELIFE  = "LIFE_PRODUCT_TYPE_WHOLE_LIFE"
	LifeProductTypeLIFEPRODUCTTYPEENDOWMENT  = "LIFE_PRODUCT_TYPE_ENDOWMENT"
	LifeProductTypeLIFEPRODUCTTYPEMONEYBACK  = "LIFE_PRODUCT_TYPE_MONEY_BACK"
	LifeProductTypeLIFEPRODUCTTYPEUNITLINKED  = "LIFE_PRODUCT_TYPE_UNIT_LINKED"
	LifeProductTypeLIFEPRODUCTTYPEGROUP  = "LIFE_PRODUCT_TYPE_GROUP"
	LifeProductTypeLIFEPRODUCTTYPEPENSION  = "LIFE_PRODUCT_TYPE_PENSION"
	LifeProductTypeLIFEPRODUCTTYPECHILD  = "LIFE_PRODUCT_TYPE_CHILD"
)
