package models

// LifeQuoteStatus represents a life_quote_status
type LifeQuoteStatus string

// LifeQuoteStatus values
const (
	LifeQuoteStatusLIFEQUOTESTATUSUNSPECIFIED LifeQuoteStatus = "LIFE_QUOTE_STATUS_UNSPECIFIED"
	LifeQuoteStatusLIFEQUOTESTATUSDRAFT  = "LIFE_QUOTE_STATUS_DRAFT"
	LifeQuoteStatusLIFEQUOTESTATUSGENERATED  = "LIFE_QUOTE_STATUS_GENERATED"
	LifeQuoteStatusLIFEQUOTESTATUSSENT  = "LIFE_QUOTE_STATUS_SENT"
	LifeQuoteStatusLIFEQUOTESTATUSVIEWED  = "LIFE_QUOTE_STATUS_VIEWED"
	LifeQuoteStatusLIFEQUOTESTATUSACCEPTED  = "LIFE_QUOTE_STATUS_ACCEPTED"
	LifeQuoteStatusLIFEQUOTESTATUSDECLINED  = "LIFE_QUOTE_STATUS_DECLINED"
	LifeQuoteStatusLIFEQUOTESTATUSEXPIRED  = "LIFE_QUOTE_STATUS_EXPIRED"
	LifeQuoteStatusLIFEQUOTESTATUSCONVERTED  = "LIFE_QUOTE_STATUS_CONVERTED"
)
