package models

// OrderProposalStatus represents a order_proposal_status
type OrderProposalStatus string

// OrderProposalStatus values
const (
	OrderProposalStatusORDERPROPOSALSTATUSUNSPECIFIED OrderProposalStatus = "ORDER_PROPOSAL_STATUS_UNSPECIFIED"
	OrderProposalStatusORDERPROPOSALSTATUSNOTSUBMITTED  = "ORDER_PROPOSAL_STATUS_NOT_SUBMITTED"
	OrderProposalStatusORDERPROPOSALSTATUSSUBMITTED  = "ORDER_PROPOSAL_STATUS_SUBMITTED"
	OrderProposalStatusORDERPROPOSALSTATUSINREVIEW  = "ORDER_PROPOSAL_STATUS_IN_REVIEW"
	OrderProposalStatusORDERPROPOSALSTATUSAPPROVED  = "ORDER_PROPOSAL_STATUS_APPROVED"
	OrderProposalStatusORDERPROPOSALSTATUSREJECTED  = "ORDER_PROPOSAL_STATUS_REJECTED"
	OrderProposalStatusORDERPROPOSALSTATUSREFUNDINITIATED  = "ORDER_PROPOSAL_STATUS_REFUND_INITIATED"
	OrderProposalStatusORDERPROPOSALSTATUSREFUNDED  = "ORDER_PROPOSAL_STATUS_REFUNDED"
)
