package models

// OrderPaymentStatus represents a order_payment_status
type OrderPaymentStatus string

// OrderPaymentStatus values
const (
	OrderPaymentStatusORDERPAYMENTSTATUSUNSPECIFIED OrderPaymentStatus = "ORDER_PAYMENT_STATUS_UNSPECIFIED"
	OrderPaymentStatusORDERPAYMENTSTATUSUNPAID  = "ORDER_PAYMENT_STATUS_UNPAID"
	OrderPaymentStatusORDERPAYMENTSTATUSPAYMENTINPROGRESS  = "ORDER_PAYMENT_STATUS_PAYMENT_IN_PROGRESS"
	OrderPaymentStatusORDERPAYMENTSTATUSPAID  = "ORDER_PAYMENT_STATUS_PAID"
	OrderPaymentStatusORDERPAYMENTSTATUSPAYMENTFAILED  = "ORDER_PAYMENT_STATUS_PAYMENT_FAILED"
	OrderPaymentStatusORDERPAYMENTSTATUSREFUNDED  = "ORDER_PAYMENT_STATUS_REFUNDED"
)
