package models

// OrderStatus represents a order_status
type OrderStatus string

// OrderStatus values
const (
	OrderStatusORDERSTATUSUNSPECIFIED OrderStatus = "ORDER_STATUS_UNSPECIFIED"
	OrderStatusORDERSTATUSPENDING  = "ORDER_STATUS_PENDING"
	OrderStatusORDERSTATUSPAYMENTINITIATED  = "ORDER_STATUS_PAYMENT_INITIATED"
	OrderStatusORDERSTATUSPAID  = "ORDER_STATUS_PAID"
	OrderStatusORDERSTATUSPOLICYISSUED  = "ORDER_STATUS_POLICY_ISSUED"
	OrderStatusORDERSTATUSCANCELLED  = "ORDER_STATUS_CANCELLED"
	OrderStatusORDERSTATUSFAILED  = "ORDER_STATUS_FAILED"
)
