package models

// PaymentMethod represents a payment_method
type PaymentMethod string

// PaymentMethod values
const (
	PaymentMethodPAYMENTMETHODUNSPECIFIED PaymentMethod = "PAYMENT_METHOD_UNSPECIFIED"
	PaymentMethodPAYMENTMETHODBKASH  = "PAYMENT_METHOD_BKASH"
	PaymentMethodPAYMENTMETHODNAGAD  = "PAYMENT_METHOD_NAGAD"
	PaymentMethodPAYMENTMETHODROCKET  = "PAYMENT_METHOD_ROCKET"
	PaymentMethodPAYMENTMETHODCARD  = "PAYMENT_METHOD_CARD"
	PaymentMethodPAYMENTMETHODBANKTRANSFER  = "PAYMENT_METHOD_BANK_TRANSFER"
	PaymentMethodPAYMENTMETHODCASH  = "PAYMENT_METHOD_CASH"
	PaymentMethodPAYMENTMETHODCHEQUE  = "PAYMENT_METHOD_CHEQUE"
)
