package models

// PricingRuleType represents a pricing_rule_type
type PricingRuleType string

// PricingRuleType values
const (
	PricingRuleTypePRICINGRULETYPEUNSPECIFIED PricingRuleType = "PRICING_RULE_TYPE_UNSPECIFIED"
	PricingRuleTypePRICINGRULETYPEBASERATE  = "PRICING_RULE_TYPE_BASE_RATE"
	PricingRuleTypePRICINGRULETYPERISKADJUSTMENT  = "PRICING_RULE_TYPE_RISK_ADJUSTMENT"
	PricingRuleTypePRICINGRULETYPEDISCOUNT  = "PRICING_RULE_TYPE_DISCOUNT"
	PricingRuleTypePRICINGRULETYPELOADING  = "PRICING_RULE_TYPE_LOADING"
	PricingRuleTypePRICINGRULETYPETAX  = "PRICING_RULE_TYPE_TAX"
	PricingRuleTypePRICINGRULETYPEFEE  = "PRICING_RULE_TYPE_FEE"
)
