package models

// ProcessingType represents a processing_type
type ProcessingType string

// ProcessingType values
const (
	ProcessingTypePROCESSINGTYPEUNSPECIFIED ProcessingType = "PROCESSING_TYPE_UNSPECIFIED"
	ProcessingTypePROCESSINGTYPEOPTIMIZATION  = "PROCESSING_TYPE_OPTIMIZATION"
	ProcessingTypePROCESSINGTYPETHUMBNAIL  = "PROCESSING_TYPE_THUMBNAIL"
	ProcessingTypePROCESSINGTYPEOCR  = "PROCESSING_TYPE_OCR"
	ProcessingTypePROCESSINGTYPEVIRUSSCAN  = "PROCESSING_TYPE_VIRUS_SCAN"
	ProcessingTypePROCESSINGTYPEVALIDATION  = "PROCESSING_TYPE_VALIDATION"
)
