package models

// ProcessingStatus represents a processing_status
type ProcessingStatus string

// ProcessingStatus values
const (
	ProcessingStatusPROCESSINGSTATUSUNSPECIFIED ProcessingStatus = "PROCESSING_STATUS_UNSPECIFIED"
	ProcessingStatusPROCESSINGSTATUSPENDING  = "PROCESSING_STATUS_PENDING"
	ProcessingStatusPROCESSINGSTATUSINPROGRESS  = "PROCESSING_STATUS_IN_PROGRESS"
	ProcessingStatusPROCESSINGSTATUSCOMPLETED  = "PROCESSING_STATUS_COMPLETED"
	ProcessingStatusPROCESSINGSTATUSFAILED  = "PROCESSING_STATUS_FAILED"
	ProcessingStatusPROCESSINGSTATUSCANCELLED  = "PROCESSING_STATUS_CANCELLED"
)
