package models

// ProposalStatus represents a proposal_status
type ProposalStatus string

// ProposalStatus values
const (
	ProposalStatusPROPOSALSTATUSUNSPECIFIED ProposalStatus = "PROPOSAL_STATUS_UNSPECIFIED"
	ProposalStatusPROPOSALSTATUSDRAFT  = "PROPOSAL_STATUS_DRAFT"
	ProposalStatusPROPOSALSTATUSSUBMITTED  = "PROPOSAL_STATUS_SUBMITTED"
	ProposalStatusPROPOSALSTATUSINREVIEW  = "PROPOSAL_STATUS_IN_REVIEW"
	ProposalStatusPROPOSALSTATUSAPPROVED  = "PROPOSAL_STATUS_APPROVED"
	ProposalStatusPROPOSALSTATUSREJECTED  = "PROPOSAL_STATUS_REJECTED"
	ProposalStatusPROPOSALSTATUSREFUNDINITIATED  = "PROPOSAL_STATUS_REFUND_INITIATED"
	ProposalStatusPROPOSALSTATUSREFUNDED  = "PROPOSAL_STATUS_REFUNDED"
	ProposalStatusPROPOSALSTATUSCANCELLED  = "PROPOSAL_STATUS_CANCELLED"
)
