package models

// PurchaseOrderStatus represents a purchase_order_status
type PurchaseOrderStatus string

// PurchaseOrderStatus values
const (
	PurchaseOrderStatusPURCHASEORDERSTATUSUNSPECIFIED PurchaseOrderStatus = "PURCHASE_ORDER_STATUS_UNSPECIFIED"
	PurchaseOrderStatusPURCHASEORDERSTATUSDRAFT  = "PURCHASE_ORDER_STATUS_DRAFT"
	PurchaseOrderStatusPURCHASEORDERSTATUSSUBMITTED  = "PURCHASE_ORDER_STATUS_SUBMITTED"
	PurchaseOrderStatusPURCHASEORDERSTATUSAPPROVED  = "PURCHASE_ORDER_STATUS_APPROVED"
	PurchaseOrderStatusPURCHASEORDERSTATUSFULFILLED  = "PURCHASE_ORDER_STATUS_FULFILLED"
	PurchaseOrderStatusPURCHASEORDERSTATUSREJECTED  = "PURCHASE_ORDER_STATUS_REJECTED"
)
