package models

// QualificationStatus represents a qualification_status
type QualificationStatus string

// QualificationStatus values
const (
	QualificationStatusQUALIFICATIONSTATUSUNSPECIFIED QualificationStatus = "QUALIFICATION_STATUS_UNSPECIFIED"
	QualificationStatusQUALIFICATIONSTATUSUNQUALIFIED  = "QUALIFICATION_STATUS_UNQUALIFIED"
	QualificationStatusQUALIFICATIONSTATUSINPROGRESS  = "QUALIFICATION_STATUS_IN_PROGRESS"
	QualificationStatusQUALIFICATIONSTATUSQUALIFIED  = "QUALIFICATION_STATUS_QUALIFIED"
	QualificationStatusQUALIFICATIONSTATUSDISQUALIFIED  = "QUALIFICATION_STATUS_DISQUALIFIED"
)
