package models

// ReserveStatus represents a reserve_status
type ReserveStatus string

// ReserveStatus values
const (
	ReserveStatusRESERVESTATUSUNSPECIFIED ReserveStatus = "RESERVE_STATUS_UNSPECIFIED"
	ReserveStatusRESERVESTATUSPENDING  = "RESERVE_STATUS_PENDING"
	ReserveStatusRESERVESTATUSCALCULATED  = "RESERVE_STATUS_CALCULATED"
	ReserveStatusRESERVESTATUSREVIEWED  = "RESERVE_STATUS_REVIEWED"
	ReserveStatusRESERVESTATUSAPPROVED  = "RESERVE_STATUS_APPROVED"
	ReserveStatusRESERVESTATUSADJUSTED  = "RESERVE_STATUS_ADJUSTED"
)
