package models

// UserType represents a user_type
type UserType string

// UserType values
const (
	UserTypeUSERTYPEUNSPECIFIED UserType = "USER_TYPE_UNSPECIFIED"
	UserTypeUSERTYPEB2CCUSTOMER  = "USER_TYPE_B2C_CUSTOMER"
	UserTypeUSERTYPEAGENT  = "USER_TYPE_AGENT"
	UserTypeUSERTYPEBUSINESSBENEFICIARY  = "USER_TYPE_BUSINESS_BENEFICIARY"
	UserTypeUSERTYPESYSTEMUSER  = "USER_TYPE_SYSTEM_USER"
	UserTypeUSERTYPEPARTNER  = "USER_TYPE_PARTNER"
	UserTypeUSERTYPEREGULATOR  = "USER_TYPE_REGULATOR"
	UserTypeUSERTYPEBUSINESSADMIN  = "USER_TYPE_BUSINESS_ADMIN"
	UserTypeUSERTYPEB2BORGADMIN  = "USER_TYPE_B2B_ORG_ADMIN"
)
