package models

// WorkflowTaskType represents a workflow_task_type
type WorkflowTaskType string

// WorkflowTaskType values
const (
	WorkflowTaskTypeWORKFLOWTASKTYPEUNSPECIFIED WorkflowTaskType = "WORKFLOW_TASK_TYPE_UNSPECIFIED"
	WorkflowTaskTypeWORKFLOWTASKTYPEAPPROVAL  = "WORKFLOW_TASK_TYPE_APPROVAL"
	WorkflowTaskTypeWORKFLOWTASKTYPEREVIEW  = "WORKFLOW_TASK_TYPE_REVIEW"
	WorkflowTaskTypeWORKFLOWTASKTYPENOTIFICATION  = "WORKFLOW_TASK_TYPE_NOTIFICATION"
	WorkflowTaskTypeWORKFLOWTASKTYPEACTION  = "WORKFLOW_TASK_TYPE_ACTION"
)
