package models

// WorkflowTaskStatus represents a workflow_task_status
type WorkflowTaskStatus string

// WorkflowTaskStatus values
const (
	WorkflowTaskStatusWORKFLOWTASKSTATUSUNSPECIFIED WorkflowTaskStatus = "WORKFLOW_TASK_STATUS_UNSPECIFIED"
	WorkflowTaskStatusWORKFLOWTASKSTATUSPENDING  = "WORKFLOW_TASK_STATUS_PENDING"
	WorkflowTaskStatusWORKFLOWTASKSTATUSINPROGRESS  = "WORKFLOW_TASK_STATUS_IN_PROGRESS"
	WorkflowTaskStatusWORKFLOWTASKSTATUSCOMPLETED  = "WORKFLOW_TASK_STATUS_COMPLETED"
	WorkflowTaskStatusWORKFLOWTASKSTATUSSKIPPED  = "WORKFLOW_TASK_STATUS_SKIPPED"
)
