// <auto-generated />
using System;
using InsuranceEngine.Underwriting.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InsuranceEngine.Underwriting.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UnderwritingDbContext))]
    partial class UnderwritingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("insurance_schema")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("quote_number_seq", "insurance_schema");

            modelBuilder.Entity("InsuranceEngine.SharedKernel.Domain.Entities.Beneficiary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuditInfo")
                        .HasColumnType("jsonb");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("KycCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferralCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReferredBy")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskScore")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("beneficiaries", "insurance_schema");
                });

            modelBuilder.Entity("InsuranceEngine.SharedKernel.Domain.Entities.BusinessBeneficiary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActivePoliciesCount")
                        .HasColumnType("integer");

                    b.Property<string>("AuditInfo")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uuid");

                    b.Property<string>("BinNumber")
                        .HasColumnType("text");

                    b.Property<string>("BusinessAddressJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessNameBn")
                        .HasColumnType("text");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactInfoJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("integer");

                    b.Property<string>("FocalPersonContact")
                        .HasColumnType("text");

                    b.Property<string>("FocalPersonContactJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("FocalPersonDesignation")
                        .HasColumnType("text");

                    b.Property<string>("FocalPersonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FocalPersonNid")
                        .HasColumnType("text");

                    b.Property<DateTime?>("IncorporationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Industry")
                        .HasColumnType("text");

                    b.Property<string>("IndustrySector")
                        .HasColumnType("text");

                    b.Property<int>("PendingActionsCount")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryContactJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("RegisteredAddressJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.Property<string>("TaxId")
                        .HasColumnType("text");

                    b.Property<string>("TinNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalEmployeesCovered")
                        .HasColumnType("integer");

                    b.Property<long>("TotalPremiumAmount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TradeLicenseExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TradeLicenseIssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TradeLicenseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId")
                        .IsUnique();

                    b.ToTable("business_beneficiaries", "insurance_schema");
                });

            modelBuilder.Entity("InsuranceEngine.SharedKernel.Domain.Entities.IndividualBeneficiary", b =>
                {
                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuditInfo")
                        .HasColumnType("jsonb");

                    b.Property<string>("BirthCertificateNumber")
                        .HasColumnType("text");

                    b.Property<string>("ContactInfoJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FatherName")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullNameBn")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("numeric");

                    b.Property<string>("MotherName")
                        .HasColumnType("text");

                    b.Property<string>("NidNumber")
                        .HasColumnType("text");

                    b.Property<string>("NomineeName")
                        .HasColumnType("text");

                    b.Property<string>("NomineeRelationship")
                        .HasColumnType("text");

                    b.Property<string>("Occupation")
                        .HasColumnType("text");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("text");

                    b.Property<string>("PermanentAddressJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("PresentAddressJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("TinNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BeneficiaryId");

                    b.ToTable("individual_beneficiaries", "insurance_schema");
                });

            modelBuilder.Entity("InsuranceEngine.Underwriting.Domain.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApplicantAge")
                        .HasColumnType("integer");

                    b.Property<string>("ApplicantOccupation")
                        .HasColumnType("text");

                    b.Property<string>("AuditInfoJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("audit_info");

                    b.Property<long>("BasePremiumAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("base_premium_amount");

                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConvertedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConvertedPolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("BDT")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InsurerProductId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSmoker")
                        .HasColumnType("boolean");

                    b.Property<string>("PremiumCalculationJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("premium_calculation");

                    b.Property<string>("PremiumPaymentMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("RiderPremiumAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("rider_premium_amount");

                    b.Property<string>("SelectedRidersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("selected_riders");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("SumAssuredAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("sum_assured_amount");

                    b.Property<string>("SumAssuredCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("BDT")
                        .HasColumnName("sum_assured_currency");

                    b.Property<long>("TaxAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("tax_amount");

                    b.Property<int>("TermYears")
                        .HasColumnType("integer");

                    b.Property<long>("TotalPremiumAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_premium_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("InsurerProductId");

                    b.HasIndex("QuoteNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("quotes", "insurance_schema");
                });

            modelBuilder.Entity("InsuranceEngine.Underwriting.Domain.Entities.UnderwritingDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AdjustedPremiumAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("adjusted_premium_amount");

                    b.Property<string>("AdjustedPremiumCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("BDT")
                        .HasColumnName("adjusted_premium_currency");

                    b.Property<string>("AdjustmentReason")
                        .HasColumnType("text");

                    b.Property<string>("AuditInfoJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("audit_info");

                    b.Property<string>("ConditionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("conditions");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsPremiumAdjusted")
                        .HasColumnType("boolean");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("RiskFactorsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("risk_factors");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("RiskScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("UnderwriterComments")
                        .HasColumnType("text");

                    b.Property<Guid?>("UnderwriterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Decision");

                    b.ToTable("underwriting_decisions", "insurance_schema");
                });

            modelBuilder.Entity("InsuranceEngine.Underwriting.Domain.Entities.UnderwritingHealthDeclaration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuditInfoJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("audit_info");

                    b.Property<decimal>("Bmi")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FamilyHistoryJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("family_history");

                    b.Property<bool>("HasFamilyHistory")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPreExistingConditions")
                        .HasColumnType("boolean");

                    b.Property<int>("HeightCm")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAlcoholConsumer")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCurrentlyHospitalized")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMedicalExamCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMedicalExamRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSmoker")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicalDocumentsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("medical_documents");

                    b.Property<DateTime?>("MedicalExamDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedicalExamResultsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("medical_exam_results");

                    b.Property<string>("OccupationRiskLevel")
                        .HasColumnType("text");

                    b.Property<string>("PreExistingConditionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("pre_existing_conditions");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId")
                        .IsUnique();

                    b.ToTable("health_declarations", "insurance_schema");
                });

            modelBuilder.Entity("InsuranceEngine.SharedKernel.Domain.Entities.BusinessBeneficiary", b =>
                {
                    b.HasOne("InsuranceEngine.SharedKernel.Domain.Entities.Beneficiary", "Beneficiary")
                        .WithOne("BusinessDetails")
                        .HasForeignKey("InsuranceEngine.SharedKernel.Domain.Entities.BusinessBeneficiary", "BeneficiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");
                });

            modelBuilder.Entity("InsuranceEngine.SharedKernel.Domain.Entities.IndividualBeneficiary", b =>
                {
                    b.HasOne("InsuranceEngine.SharedKernel.Domain.Entities.Beneficiary", "Beneficiary")
                        .WithOne("IndividualDetails")
                        .HasForeignKey("InsuranceEngine.SharedKernel.Domain.Entities.IndividualBeneficiary", "BeneficiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");
                });

            modelBuilder.Entity("InsuranceEngine.SharedKernel.Domain.Entities.Beneficiary", b =>
                {
                    b.Navigation("BusinessDetails");

                    b.Navigation("IndividualDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
