// @generated by protoc-gen-es v2.2.2 with parameter "target=ts,import_extension=none"
// @generated from file insuretech/authz/entity/v1/enums.proto (package insuretech.authz.entity.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file insuretech/authz/entity/v1/enums.proto.
 */
export const file_insuretech_authz_entity_v1_enums: GenFile = /*@__PURE__*/
  fileDesc("CiZpbnN1cmV0ZWNoL2F1dGh6L2VudGl0eS92MS9lbnVtcy5wcm90bxIaaW5zdXJldGVjaC5hdXRoei5lbnRpdHkudjEqkAEKBlBvcnRhbBIWChJQT1JUQUxfVU5TUEVDSUZJRUQQABIRCg1QT1JUQUxfU1lTVEVNEAESEwoPUE9SVEFMX0JVU0lORVNTEAISDgoKUE9SVEFMX0IyQhADEhAKDFBPUlRBTF9BR0VOVBAEEhQKEFBPUlRBTF9SRUdVTEFUT1IQBRIOCgpQT1JUQUxfQjJDEAYqXgoMUG9saWN5RWZmZWN0Eh0KGVBPTElDWV9FRkZFQ1RfVU5TUEVDSUZJRUQQABIXChNQT0xJQ1lfRUZGRUNUX0FMTE9XEAESFgoSUE9MSUNZX0VGRkVDVF9ERU5ZEAJChgIKHmNvbS5pbnN1cmV0ZWNoLmF1dGh6LmVudGl0eS52MUIKRW51bXNQcm90b1ABWk1naXRodWIuY29tL25ld2FnZS1zYWludC9pbnN1cmV0ZWNoL2dlbi9nby9pbnN1cmV0ZWNoL2F1dGh6L2VudGl0eS92MTtlbnRpdHl2MaICA0lBRaoCGkluc3VyZXRlY2guQXV0aHouRW50aXR5LlYxygIaSW5zdXJldGVjaFxBdXRoelxFbnRpdHlcVjHiAiZJbnN1cmV0ZWNoXEF1dGh6XEVudGl0eVxWMVxHUEJNZXRhZGF0YeoCHUluc3VyZXRlY2g6OkF1dGh6OjpFbnRpdHk6OlYxYgZwcm90bzM");

/**
 * Portal identifies which portal context the request comes from.
 * Domain format in Casbin: "portal:tenant_id"
 *
 * @generated from enum insuretech.authz.entity.v1.Portal
 */
export enum Portal {
  /**
   * @generated from enum value: PORTAL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Internal admin portal (SYSTEM_USER)
   *
   * @generated from enum value: PORTAL_SYSTEM = 1;
   */
  SYSTEM = 1,

  /**
   * Business/corporate portal (BUSINESS_BENEFICIARY)
   *
   * @generated from enum value: PORTAL_BUSINESS = 2;
   */
  BUSINESS = 2,

  /**
   * Partner portal (PARTNER — insurers, brokers, TPAs)
   *
   * @generated from enum value: PORTAL_B2B = 3;
   */
  B2B = 3,

  /**
   * Agent/field-staff portal (AGENT)
   *
   * @generated from enum value: PORTAL_AGENT = 4;
   */
  AGENT = 4,

  /**
   * Regulatory/auditor portal (REGULATOR — read-only)
   *
   * @generated from enum value: PORTAL_REGULATOR = 5;
   */
  REGULATOR = 5,

  /**
   * Customer mobile portal (B2C_CUSTOMER)
   *
   * @generated from enum value: PORTAL_B2C = 6;
   */
  B2C = 6,
}

/**
 * Describes the enum insuretech.authz.entity.v1.Portal.
 */
export const PortalSchema: GenEnum<Portal> = /*@__PURE__*/
  enumDesc(file_insuretech_authz_entity_v1_enums, 0);

/**
 * PolicyEffect mirrors Casbin allow/deny semantics.
 *
 * @generated from enum insuretech.authz.entity.v1.PolicyEffect
 */
export enum PolicyEffect {
  /**
   * @generated from enum value: POLICY_EFFECT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: POLICY_EFFECT_ALLOW = 1;
   */
  ALLOW = 1,

  /**
   * @generated from enum value: POLICY_EFFECT_DENY = 2;
   */
  DENY = 2,
}

/**
 * Describes the enum insuretech.authz.entity.v1.PolicyEffect.
 */
export const PolicyEffectSchema: GenEnum<PolicyEffect> = /*@__PURE__*/
  enumDesc(file_insuretech_authz_entity_v1_enums, 1);

