// @generated by protoc-gen-es v2.2.2 with parameter "target=ts,import_extension=none"
// @generated from file insuretech/authz/entity/v1/role_mfa_config.proto (package insuretech.authz.entity.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_insuretech_common_v1_db } from "../../../common/v1/db_pb";
import { file_insuretech_authz_entity_v1_enums } from "./enums_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file insuretech/authz/entity/v1/role_mfa_config.proto.
 */
export const file_insuretech_authz_entity_v1_role_mfa_config: GenFile = /*@__PURE__*/
  fileDesc("CjBpbnN1cmV0ZWNoL2F1dGh6L2VudGl0eS92MS9yb2xlX21mYV9jb25maWcucHJvdG8SGmluc3VyZXRlY2guYXV0aHouZW50aXR5LnYxItEDCg1Sb2xlTUZBQ29uZmlnEmcKB3JvbGVfaWQYASABKAlCVpK1GFIKB3JvbGVfaWQSBFVVSUQYASgBSj0KBXJvbGVzEgdyb2xlX2lkGgxhdXRoel9zY2hlbWEgAzIbZmtfcm9sZV9tZmFfY29uZmlnc19yb2xlX2lkEjoKDG1mYV9yZXF1aXJlZBgCIAEoCEIkkrUYIAoMbWZhX3JlcXVpcmVkEgdCT09MRUFOGAE6BWZhbHNlEhMKC21mYV9tZXRob2RzGAMgAygJEioKCnVwZGF0ZWRfYnkYBCABKAlCFpK1GBIKCnVwZGF0ZWRfYnkSBFVVSUQSbwoKdXBkYXRlZF9hdBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCP5K1GDsKCnVwZGF0ZWRfYXQSGFRJTUVTVEFNUCBXSVRIIFRJTUUgWk9ORRgBOhFDVVJSRU5UX1RJTUVTVEFNUDppirUYZQoQcm9sZV9tZmFfY29uZmlncxIMYXV0aHpfc2NoZW1hGAggASo9UGVyLXJvbGUgTUZBIHJlcXVpcmVtZW50cyB0aGF0IG92ZXJyaWRlIHBvcnRhbC1sZXZlbCBkZWZhdWx0czgBQo4CCh5jb20uaW5zdXJldGVjaC5hdXRoei5lbnRpdHkudjFCElJvbGVNZmFDb25maWdQcm90b1ABWk1naXRodWIuY29tL25ld2FnZS1zYWludC9pbnN1cmV0ZWNoL2dlbi9nby9pbnN1cmV0ZWNoL2F1dGh6L2VudGl0eS92MTtlbnRpdHl2MaICA0lBRaoCGkluc3VyZXRlY2guQXV0aHouRW50aXR5LlYxygIaSW5zdXJldGVjaFxBdXRoelxFbnRpdHlcVjHiAiZJbnN1cmV0ZWNoXEF1dGh6XEVudGl0eVxWMVxHUEJNZXRhZGF0YeoCHUluc3VyZXRlY2g6OkF1dGh6OjpFbnRpdHk6OlYxYgZwcm90bzM", [file_google_protobuf_timestamp, file_insuretech_common_v1_db, file_insuretech_authz_entity_v1_enums]);

/**
 * ---------------------------------------------------------------------------
 * 8. RoleMFAConfig — per-role MFA override (overrides portal-level default)
 * ---------------------------------------------------------------------------
 *
 * @generated from message insuretech.authz.entity.v1.RoleMFAConfig
 */
export type RoleMFAConfig = Message<"insuretech.authz.entity.v1.RoleMFAConfig"> & {
  /**
   * @generated from field: string role_id = 1;
   */
  roleId: string;

  /**
   * @generated from field: bool mfa_required = 2;
   */
  mfaRequired: boolean;

  /**
   * JSONB: ["totp","sms"]
   *
   * @generated from field: repeated string mfa_methods = 3;
   */
  mfaMethods: string[];

  /**
   * @generated from field: string updated_by = 4;
   */
  updatedBy: string;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 5;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message insuretech.authz.entity.v1.RoleMFAConfig.
 * Use `create(RoleMFAConfigSchema)` to create a new message.
 */
export const RoleMFAConfigSchema: GenMessage<RoleMFAConfig> = /*@__PURE__*/
  messageDesc(file_insuretech_authz_entity_v1_role_mfa_config, 0);

