ProductPlansListingResponse:
  type: object
  properties:
    plans:
      type: array
      items:
        $ref: '#/components/schemas/ProductPlan'
  description: Response payload for product plans listing operation. Returns operation
    results and status.
