// @generated by protoc-gen-es v2.2.2 with parameter "target=ts,import_extension=none"
// @generated from file insuretech/support/entity/v1/ticket_message.proto (package insuretech.support.entity.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { AuditInfo } from "../../../common/v1/types_pb";
import { file_insuretech_common_v1_types } from "../../../common/v1/types_pb";
import { file_insuretech_common_v1_db } from "../../../common/v1/db_pb";
import { file_insuretech_common_v1_security } from "../../../common/v1/security_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file insuretech/support/entity/v1/ticket_message.proto.
 */
export const file_insuretech_support_entity_v1_ticket_message: GenFile = /*@__PURE__*/
  fileDesc("CjFpbnN1cmV0ZWNoL3N1cHBvcnQvZW50aXR5L3YxL3RpY2tldF9tZXNzYWdlLnByb3RvEhxpbnN1cmV0ZWNoLnN1cHBvcnQuZW50aXR5LnYxIrYGCg1UaWNrZXRNZXNzYWdlEjkKAmlkGAEgASgJQi2StRgpCgptZXNzYWdlX2lkEgRVVUlEGAEoAToRZ2VuX3JhbmRvbV91dWlkKCkSdQoJdGlja2V0X2lkGAIgASgJQmKStRheCgl0aWNrZXRfaWQSBFVVSUQYAUomCgd0aWNrZXRzEgl0aWNrZXRfaWQaDnN1cHBvcnRfc2NoZW1hIANSIQodaWR4X3RpY2tldF9tZXNzYWdlc190aWNrZXRfaWQQAhJMCglzZW5kZXJfaWQYAyABKAlCOZK1GDUKCXNlbmRlcl9pZBIEVVVJRBgBSiAKBXVzZXJzEgd1c2VyX2lkGgxhdXRobl9zY2hlbWEgAhJSCgR0eXBlGAQgASgOMikuaW5zdXJldGVjaC5zdXBwb3J0LmVudGl0eS52MS5NZXNzYWdlVHlwZUIZkrUYFQoEdHlwZRILVkFSQ0hBUigyMCkYARJnCgdjb250ZW50GAUgASgJQlaStRgRCgdjb250ZW50EgRURVhUGAHQtRgB4LUYAfC1GAGCthgxU3VwcG9ydCB0aWNrZXQgY29tbXVuaWNhdGlvbiBhbmQgaXNzdWUgcmVzb2x1dGlvbhJBCgthdHRhY2htZW50cxgGIAEoCUIskrUYKAoLYXR0YWNobWVudHMSBUpTT05CWhBGaWxlIGF0dGFjaG1lbnRzeAESXwoLaXNfaW50ZXJuYWwYByABKAhCSpK1GEYKC2lzX2ludGVybmFsEgdCT09MRUFOOgVmYWxzZVonSW50ZXJuYWwgbm90ZSAobm90IHZpc2libGUgdG8gY3VzdG9tZXIpEnkKCmF1ZGl0X2luZm8YCCABKAsyHy5pbnN1cmV0ZWNoLmNvbW1vbi52MS5BdWRpdEluZm9CRJK1GEAKCmF1ZGl0X2luZm8SBUpTT05CGAE6Cyd7fSc6Ompzb25iWhpBdWRpdCB0cmFpbCBzdG9yZWQgYXMgSlNPTngBOkmKtRhFCg90aWNrZXRfbWVzc2FnZXMSDnN1cHBvcnRfc2NoZW1hGFggASocVGlja2V0IGNvbnZlcnNhdGlvbiBtZXNzYWdlczgBKpcBCgtNZXNzYWdlVHlwZRIcChhNRVNTQUdFX1RZUEVfVU5TUEVDSUZJRUQQABIWChJNRVNTQUdFX1RZUEVfUkVQTFkQARIVChFNRVNTQUdFX1RZUEVfTk9URRACEh4KGk1FU1NBR0VfVFlQRV9TVEFUVVNfQ0hBTkdFEAMSGwoXTUVTU0FHRV9UWVBFX0FTU0lHTk1FTlQQBEKaAgogY29tLmluc3VyZXRlY2guc3VwcG9ydC5lbnRpdHkudjFCElRpY2tldE1lc3NhZ2VQcm90b1ABWk9naXRodWIuY29tL25ld2FnZS1zYWludC9pbnN1cmV0ZWNoL2dlbi9nby9pbnN1cmV0ZWNoL3N1cHBvcnQvZW50aXR5L3YxO2VudGl0eXYxogIDSVNFqgIcSW5zdXJldGVjaC5TdXBwb3J0LkVudGl0eS5WMcoCHEluc3VyZXRlY2hcU3VwcG9ydFxFbnRpdHlcVjHiAihJbnN1cmV0ZWNoXFN1cHBvcnRcRW50aXR5XFYxXEdQQk1ldGFkYXRh6gIfSW5zdXJldGVjaDo6U3VwcG9ydDo6RW50aXR5OjpWMWIGcHJvdG8z", [file_insuretech_common_v1_types, file_insuretech_common_v1_db, file_insuretech_common_v1_security]);

/**
 * Ticket message/reply
 *
 * @generated from message insuretech.support.entity.v1.TicketMessage
 */
export type TicketMessage = Message<"insuretech.support.entity.v1.TicketMessage"> & {
  /**
   * @inject_tag: gorm:"primaryKey;column:message_id;not null"
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @inject_tag: gorm:"column:ticket_id;not null"
   *
   * @generated from field: string ticket_id = 2;
   */
  ticketId: string;

  /**
   * @inject_tag: gorm:"column:sender_id;not null"
   *
   * @generated from field: string sender_id = 3;
   */
  senderId: string;

  /**
   * @inject_tag: gorm:"column:type;not null;serializer:proto_enum"
   *
   * @generated from field: insuretech.support.entity.v1.MessageType type = 4;
   */
  type: MessageType;

  /**
   * @inject_tag: gorm:"column:content;not null"
   *
   * @generated from field: string content = 5;
   */
  content: string;

  /**
   * @inject_tag: gorm:"column:attachments"
   *
   * @generated from field: string attachments = 6;
   */
  attachments: string;

  /**
   * @inject_tag: gorm:"column:is_internal"
   *
   * @generated from field: bool is_internal = 7;
   */
  isInternal: boolean;

  /**
   * @inject_tag: gorm:"column:audit_info;not null"
   *
   * @generated from field: insuretech.common.v1.AuditInfo audit_info = 8;
   */
  auditInfo?: AuditInfo;
};

/**
 * Describes the message insuretech.support.entity.v1.TicketMessage.
 * Use `create(TicketMessageSchema)` to create a new message.
 */
export const TicketMessageSchema: GenMessage<TicketMessage> = /*@__PURE__*/
  messageDesc(file_insuretech_support_entity_v1_ticket_message, 0);

/**
 * @generated from enum insuretech.support.entity.v1.MessageType
 */
export enum MessageType {
  /**
   * @generated from enum value: MESSAGE_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MESSAGE_TYPE_REPLY = 1;
   */
  REPLY = 1,

  /**
   * @generated from enum value: MESSAGE_TYPE_NOTE = 2;
   */
  NOTE = 2,

  /**
   * @generated from enum value: MESSAGE_TYPE_STATUS_CHANGE = 3;
   */
  STATUS_CHANGE = 3,

  /**
   * @generated from enum value: MESSAGE_TYPE_ASSIGNMENT = 4;
   */
  ASSIGNMENT = 4,
}

/**
 * Describes the enum insuretech.support.entity.v1.MessageType.
 */
export const MessageTypeSchema: GenEnum<MessageType> = /*@__PURE__*/
  enumDesc(file_insuretech_support_entity_v1_ticket_message, 0);

