// <auto-generated />
using System;
using System.Collections.Generic;
using InsuranceEngine.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InsuranceEngine.Service.Migrations
{
    [DbContext(typeof(InsuranceEngineDbContext))]
    [Migration("20260118162053_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InsuranceEngine.Domain.Entities.Beneficiary", b =>
                {
                    b.Property<Guid>("BeneficiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("beneficiary_id");

                    b.Property<string>("BeneficiaryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("beneficiary_code");

                    b.Property<DateTime?>("KycCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kyc_completed_at");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kyc_status");

                    b.Property<string>("PartnerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("partner_id");

                    b.Property<Guid?>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<string>("ReferralCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referral_code");

                    b.Property<string>("ReferredBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referred_by");

                    b.Property<string>("RiskScore")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("risk_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("BeneficiaryId");

                    b.ToTable("beneficiaries", (string)null);
                });

            modelBuilder.Entity("InsuranceEngine.Domain.Entities.BeneficiaryBusiness", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uuid")
                        .HasColumnName("beneficiary_id");

                    b.Property<string>("BinNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bin_number");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("business_name");

                    b.Property<string>("BusinessNameBn")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("business_name_bn");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("business_type");

                    b.Property<int?>("EmployeeCount")
                        .HasColumnType("integer")
                        .HasColumnName("employee_count");

                    b.Property<string>("FocalPersonDesignation")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("focal_person_designation");

                    b.Property<string>("FocalPersonName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("focal_person_name");

                    b.Property<string>("FocalPersonNid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("focal_person_nid");

                    b.Property<DateTime?>("IncorporationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("incorporation_date");

                    b.Property<string>("IndustrySector")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("industry_sector");

                    b.Property<string>("TinNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tin_number");

                    b.Property<DateTime?>("TradeLicenseExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trade_license_expiry_date");

                    b.Property<DateTime?>("TradeLicenseIssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trade_license_issue_date");

                    b.Property<string>("TradeLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trade_license_number");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId")
                        .IsUnique();

                    b.ToTable("beneficiary_businesses", (string)null);
                });

            modelBuilder.Entity("InsuranceEngine.Domain.Entities.BeneficiaryIndividual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uuid")
                        .HasColumnName("beneficiary_id");

                    b.Property<string>("BirthCertificateNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("birth_certificate_number");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("FullNameBn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name_bn");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gender");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("marital_status");

                    b.Property<string>("NidNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nid_number");

                    b.Property<string>("NomineeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nominee_name");

                    b.Property<string>("NomineeRelationship")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nominee_relationship");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("occupation");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("passport_number");

                    b.Property<string>("TinNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tin_number");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId")
                        .IsUnique();

                    b.ToTable("beneficiary_individuals", (string)null);
                });

            modelBuilder.Entity("InsuranceEngine.Domain.Entities.Error", b =>
                {
                    b.Property<Guid>("ErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("error_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Dictionary<string, string>>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("DocumentationUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("documentation_url");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<int?>("RetryAfterSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("retry_after_seconds");

                    b.Property<bool>("Retryable")
                        .HasColumnType("boolean")
                        .HasColumnName("retryable");

                    b.HasKey("ErrorId");

                    b.ToTable("errors", (string)null);
                });

            modelBuilder.Entity("InsuranceEngine.Domain.Entities.FieldViolation", b =>
                {
                    b.Property<Guid>("FieldViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("field_violation_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("ErrorId")
                        .HasColumnType("uuid")
                        .HasColumnName("error_id");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field");

                    b.Property<string>("RejectedValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejected_value");

                    b.HasKey("FieldViolationId");

                    b.HasIndex("ErrorId");

                    b.ToTable("field_violations", (string)null);
                });

            modelBuilder.Entity("InsuranceEngine.Domain.Entities.Beneficiary", b =>
                {
                    b.OwnsOne("InsuranceEngine.Domain.Entities.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("BeneficiaryId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deleted_by");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("updated_by");

                            b1.HasKey("BeneficiaryId");

                            b1.ToTable("beneficiaries");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("InsuranceEngine.Domain.Entities.BeneficiaryBusiness", b =>
                {
                    b.HasOne("InsuranceEngine.Domain.Entities.Beneficiary", "Beneficiary")
                        .WithOne("BusinessDetails")
                        .HasForeignKey("InsuranceEngine.Domain.Entities.BeneficiaryBusiness", "BeneficiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("InsuranceEngine.Domain.Entities.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("BeneficiaryBusinessId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deleted_by");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("updated_by");

                            b1.HasKey("BeneficiaryBusinessId");

                            b1.ToTable("beneficiary_businesses");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryBusinessId");
                        });

                    b.OwnsOne("InsuranceEngine.Domain.Entities.Address", "BusinessAddress", b1 =>
                        {
                            b1.Property<Guid>("BeneficiaryBusinessId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AddressLine1")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("business_address_line1");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("business_address_line2");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("business_city");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("business_country");

                            b1.Property<string>("District")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("business_district");

                            b1.Property<string>("Division")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("business_division");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("numeric")
                                .HasColumnName("business_latitude");

                            b1.Property<decimal?>("Longitude")
                                .HasColumnType("numeric")
                                .HasColumnName("business_longitude");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("business_postal_code");

                            b1.HasKey("BeneficiaryBusinessId");

                            b1.ToTable("beneficiary_businesses");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryBusinessId");
                        });

                    b.OwnsOne("InsuranceEngine.Domain.Entities.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("BeneficiaryBusinessId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AlternateMobile")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("contact_alternate_mobile");

                            b1.Property<string>("Email")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("contact_email");

                            b1.Property<string>("Landline")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("contact_landline");

                            b1.Property<string>("MobileNumber")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("contact_mobile_number");

                            b1.HasKey("BeneficiaryBusinessId");

                            b1.ToTable("beneficiary_businesses");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryBusinessId");
                        });

                    b.OwnsOne("InsuranceEngine.Domain.Entities.ContactInfo", "FocalPersonContact", b1 =>
                        {
                            b1.Property<Guid>("BeneficiaryBusinessId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AlternateMobile")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("focal_person_alternate_mobile");

                            b1.Property<string>("Email")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("focal_person_email");

                            b1.Property<string>("Landline")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("focal_person_landline");

                            b1.Property<string>("MobileNumber")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("focal_person_mobile_number");

                            b1.HasKey("BeneficiaryBusinessId");

                            b1.ToTable("beneficiary_businesses");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryBusinessId");
                        });

                    b.OwnsOne("InsuranceEngine.Domain.Entities.Address", "RegisteredAddress", b1 =>
                        {
                            b1.Property<Guid>("BeneficiaryBusinessId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AddressLine1")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("registered_address_line1");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("registered_address_line2");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("registered_city");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("registered_country");

                            b1.Property<string>("District")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("registered_district");

                            b1.Property<string>("Division")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("registered_division");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("numeric")
                                .HasColumnName("registered_latitude");

                            b1.Property<decimal?>("Longitude")
                                .HasColumnType("numeric")
                                .HasColumnName("registered_longitude");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("registered_postal_code");

                            b1.HasKey("BeneficiaryBusinessId");

                            b1.ToTable("beneficiary_businesses");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryBusinessId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Beneficiary");

                    b.Navigation("BusinessAddress")
                        .IsRequired();

                    b.Navigation("ContactInfo")
                        .IsRequired();

                    b.Navigation("FocalPersonContact")
                        .IsRequired();

                    b.Navigation("RegisteredAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("InsuranceEngine.Domain.Entities.BeneficiaryIndividual", b =>
                {
                    b.HasOne("InsuranceEngine.Domain.Entities.Beneficiary", "Beneficiary")
                        .WithOne("IndividualDetails")
                        .HasForeignKey("InsuranceEngine.Domain.Entities.BeneficiaryIndividual", "BeneficiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("InsuranceEngine.Domain.Entities.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("BeneficiaryIndividualId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deleted_by");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("updated_by");

                            b1.HasKey("BeneficiaryIndividualId");

                            b1.ToTable("beneficiary_individuals");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryIndividualId");
                        });

                    b.OwnsOne("InsuranceEngine.Domain.Entities.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("BeneficiaryIndividualId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AlternateMobile")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("alternate_mobile");

                            b1.Property<string>("Email")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email");

                            b1.Property<string>("Landline")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("landline");

                            b1.Property<string>("MobileNumber")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("mobile_number");

                            b1.HasKey("BeneficiaryIndividualId");

                            b1.ToTable("beneficiary_individuals");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryIndividualId");
                        });

                    b.OwnsOne("InsuranceEngine.Domain.Entities.Address", "PermanentAddress", b1 =>
                        {
                            b1.Property<Guid>("BeneficiaryIndividualId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AddressLine1")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("permanent_address_line1");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("permanent_address_line2");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("permanent_city");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("permanent_country");

                            b1.Property<string>("District")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("permanent_district");

                            b1.Property<string>("Division")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("permanent_division");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("numeric")
                                .HasColumnName("permanent_latitude");

                            b1.Property<decimal?>("Longitude")
                                .HasColumnType("numeric")
                                .HasColumnName("permanent_longitude");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("permanent_postal_code");

                            b1.HasKey("BeneficiaryIndividualId");

                            b1.ToTable("beneficiary_individuals");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryIndividualId");
                        });

                    b.OwnsOne("InsuranceEngine.Domain.Entities.Address", "PresentAddress", b1 =>
                        {
                            b1.Property<Guid>("BeneficiaryIndividualId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AddressLine1")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("present_address_line1");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("present_address_line2");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("present_city");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("present_country");

                            b1.Property<string>("District")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("present_district");

                            b1.Property<string>("Division")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("present_division");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("numeric")
                                .HasColumnName("present_latitude");

                            b1.Property<decimal?>("Longitude")
                                .HasColumnType("numeric")
                                .HasColumnName("present_longitude");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("present_postal_code");

                            b1.HasKey("BeneficiaryIndividualId");

                            b1.ToTable("beneficiary_individuals");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryIndividualId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Beneficiary");

                    b.Navigation("ContactInfo")
                        .IsRequired();

                    b.Navigation("PermanentAddress")
                        .IsRequired();

                    b.Navigation("PresentAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("InsuranceEngine.Domain.Entities.FieldViolation", b =>
                {
                    b.HasOne("InsuranceEngine.Domain.Entities.Error", "Error")
                        .WithMany("FieldViolations")
                        .HasForeignKey("ErrorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Error");
                });

            modelBuilder.Entity("InsuranceEngine.Domain.Entities.Beneficiary", b =>
                {
                    b.Navigation("BusinessDetails");

                    b.Navigation("IndividualDetails");
                });

            modelBuilder.Entity("InsuranceEngine.Domain.Entities.Error", b =>
                {
                    b.Navigation("FieldViolations");
                });
#pragma warning restore 612, 618
        }
    }
}
