WorkflowConfigType:
  type: string
  enum:
  - WORKFLOW_CONFIG_TYPE_UNSPECIFIED
  - WORKFLOW_CONFIG_TYPE_QUOTATION_APPROVAL
  - WORKFLOW_CONFIG_TYPE_PLAN_CHANGES
  - WORKFLOW_CONFIG_TYPE_PAYMENT_AUTHORIZATION
  - WORKFLOW_CONFIG_TYPE_POLICY_RENEWALS
  description: 'Type categorization for workflow config. Options: WORKFLOW_CONFIG_TYPE_UNSPECIFIED,
    WORKFLOW_CONFIG_TYPE_QUOTATION_APPROVAL, WORKFLOW_CONFIG_TYPE_PLAN_CHANGES, WORKFLOW_CONFIG_TYPE_PAYMENT_AUTHORIZATION,
    WORKFLOW_CONFIG_TYPE_POLICY_RENEWALS.'
