// @generated by protoc-gen-es v2.2.2 with parameter "target=ts,import_extension=none"
// @generated from file insuretech/mfs/entity/v1/mfs_integration.proto (package insuretech.mfs.entity.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { AuditInfo } from "../../../common/v1/types_pb";
import { file_insuretech_common_v1_types } from "../../../common/v1/types_pb";
import { file_insuretech_common_v1_db } from "../../../common/v1/db_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file insuretech/mfs/entity/v1/mfs_integration.proto.
 */
export const file_insuretech_mfs_entity_v1_mfs_integration: GenFile = /*@__PURE__*/
  fileDesc("Ci5pbnN1cmV0ZWNoL21mcy9lbnRpdHkvdjEvbWZzX2ludGVncmF0aW9uLnByb3RvEhhpbnN1cmV0ZWNoLm1mcy5lbnRpdHkudjEi3gUKDk1GU0ludGVncmF0aW9uEj0KAmlkGAEgASgJQjGStRgtCg5pbnRlZ3JhdGlvbl9pZBIEVVVJRBgBKAE6EWdlbl9yYW5kb21fdXVpZCgpEn0KCHByb3ZpZGVyGAIgASgOMiUuaW5zdXJldGVjaC5tZnMuZW50aXR5LnYxLk1GU1Byb3ZpZGVyQkSStRhACghwcm92aWRlchILVkFSQ0hBUig1MCkYASABUiMKHWlkeF9tZnNfaW50ZWdyYXRpb25zX3Byb3ZpZGVyEAIYARI4CgxhcGlfYmFzZV91cmwYAyABKAlCIpK1GB4KDGFwaV9iYXNlX3VybBIMVkFSQ0hBUigyNTUpGAESNAoLbWVyY2hhbnRfaWQYBCABKAlCH5K1GBsKC21lcmNoYW50X2lkEgxWQVJDSEFSKDEwMCkSSwoPYXBpX2NyZWRlbnRpYWxzGAUgASgJQjKStRguCg9hcGlfY3JlZGVudGlhbHMSBFRFWFRaFUVuY3J5cHRlZCBjcmVkZW50aWFscxIxCglpc19hY3RpdmUYBiABKAhCHpK1GBoKCWlzX2FjdGl2ZRIHQk9PTEVBTjoEdHJ1ZRJGCgZjb25maWcYByABKAlCNpK1GDIKBmNvbmZpZxIFSlNPTkJaH1Byb3ZpZGVyLXNwZWNpZmljIGNvbmZpZ3VyYXRpb254ARJ5CgphdWRpdF9pbmZvGAggASgLMh8uaW5zdXJldGVjaC5jb21tb24udjEuQXVkaXRJbmZvQkSStRhACgphdWRpdF9pbmZvEgVKU09OQhgBOgsne30nOjpqc29uYloaQXVkaXQgdHJhaWwgc3RvcmVkIGFzIEpTT054ATpbirUYVwoQbWZzX2ludGVncmF0aW9ucxIOcGF5bWVudF9zY2hlbWEYJiABKi1Nb2JpbGUgRmluYW5jaWFsIFNlcnZpY2VzIGludGVncmF0aW9uIGNvbmZpZ3M4ASqhAQoLTUZTUHJvdmlkZXISHAoYTUZTX1BST1ZJREVSX1VOU1BFQ0lGSUVEEAASFgoSTUZTX1BST1ZJREVSX0JLQVNIEAESFgoSTUZTX1BST1ZJREVSX05BR0FEEAISFwoTTUZTX1BST1ZJREVSX1JPQ0tFVBADEhUKEU1GU19QUk9WSURFUl9VUEFZEAQSFAoQTUZTX1BST1ZJREVSX1RBUBAFQoMCChxjb20uaW5zdXJldGVjaC5tZnMuZW50aXR5LnYxQhNNZnNJbnRlZ3JhdGlvblByb3RvUAFaS2dpdGh1Yi5jb20vbmV3YWdlLXNhaW50L2luc3VyZXRlY2gvZ2VuL2dvL2luc3VyZXRlY2gvbWZzL2VudGl0eS92MTtlbnRpdHl2MaICA0lNRaoCGEluc3VyZXRlY2guTWZzLkVudGl0eS5WMcoCGEluc3VyZXRlY2hcTWZzXEVudGl0eVxWMeICJEluc3VyZXRlY2hcTWZzXEVudGl0eVxWMVxHUEJNZXRhZGF0YeoCG0luc3VyZXRlY2g6Ok1mczo6RW50aXR5OjpWMWIGcHJvdG8z", [file_insuretech_common_v1_types, file_insuretech_common_v1_db]);

/**
 * MFS integration config (FR-073 to FR-075)
 *
 * @generated from message insuretech.mfs.entity.v1.MFSIntegration
 */
export type MFSIntegration = Message<"insuretech.mfs.entity.v1.MFSIntegration"> & {
  /**
   * @inject_tag: gorm:"primaryKey;column:integration_id;not null"
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @inject_tag: gorm:"column:provider;not null;serializer:proto_enum"
   *
   * @generated from field: insuretech.mfs.entity.v1.MFSProvider provider = 2;
   */
  provider: MFSProvider;

  /**
   * @inject_tag: gorm:"column:api_base_url;not null"
   *
   * @generated from field: string api_base_url = 3;
   */
  apiBaseUrl: string;

  /**
   * @inject_tag: gorm:"column:merchant_id"
   *
   * @generated from field: string merchant_id = 4;
   */
  merchantId: string;

  /**
   * @inject_tag: gorm:"column:api_credentials"
   *
   * @generated from field: string api_credentials = 5;
   */
  apiCredentials: string;

  /**
   * @inject_tag: gorm:"column:is_active"
   *
   * @generated from field: bool is_active = 6;
   */
  isActive: boolean;

  /**
   * @inject_tag: gorm:"column:config"
   *
   * @generated from field: string config = 7;
   */
  config: string;

  /**
   * @inject_tag: gorm:"column:audit_info;not null"
   *
   * @generated from field: insuretech.common.v1.AuditInfo audit_info = 8;
   */
  auditInfo?: AuditInfo;
};

/**
 * Describes the message insuretech.mfs.entity.v1.MFSIntegration.
 * Use `create(MFSIntegrationSchema)` to create a new message.
 */
export const MFSIntegrationSchema: GenMessage<MFSIntegration> = /*@__PURE__*/
  messageDesc(file_insuretech_mfs_entity_v1_mfs_integration, 0);

/**
 * @generated from enum insuretech.mfs.entity.v1.MFSProvider
 */
export enum MFSProvider {
  /**
   * @generated from enum value: MFS_PROVIDER_UNSPECIFIED = 0;
   */
  MFS_PROVIDER_UNSPECIFIED = 0,

  /**
   * @generated from enum value: MFS_PROVIDER_BKASH = 1;
   */
  MFS_PROVIDER_BKASH = 1,

  /**
   * @generated from enum value: MFS_PROVIDER_NAGAD = 2;
   */
  MFS_PROVIDER_NAGAD = 2,

  /**
   * @generated from enum value: MFS_PROVIDER_ROCKET = 3;
   */
  MFS_PROVIDER_ROCKET = 3,

  /**
   * @generated from enum value: MFS_PROVIDER_UPAY = 4;
   */
  MFS_PROVIDER_UPAY = 4,

  /**
   * @generated from enum value: MFS_PROVIDER_TAP = 5;
   */
  MFS_PROVIDER_TAP = 5,
}

/**
 * Describes the enum insuretech.mfs.entity.v1.MFSProvider.
 */
export const MFSProviderSchema: GenEnum<MFSProvider> = /*@__PURE__*/
  enumDesc(file_insuretech_mfs_entity_v1_mfs_integration, 0);

