export interface Partner {
	id: string;
	name: string;
	type: 'HOSPITAL' | 'PHARMACY' | 'DOCTOR' | 'AMBULANCE' | 'AUTO_REPAIR' | 'LAPTOP_REPAIR' | 'MOBILE_REPAIR';
	category: 'LIFE' | 'NON_LIFE';
	status: 'ACTIVE' | 'PENDING' | 'INACTIVE';
	email: string;
	phone: string;
	address: string;
	location: string;
	tradeLicense?: string;
	tinNumber?: string;
	
	// Discount config
	discountEnabled: boolean;
	discountPercentage: number;
	minDiscount: number;
	maxDiscount: number;
	discountType: string;
	
	// Cashless config
	cashlessEnabled: boolean;
	cashlessLimit: number;
	autoApprovalThreshold: number;
	preAuthRequired: boolean;
	authValidityDays: number;
	requiredDocuments: string[];
	
	// Additional fields
	rating?: number;
	services?: number;
	outlets?: number;
	vehicles?: number;
	specialty?: string;
	brands?: string;
	serviceType?: string;
}

// LIFE INSURANCE PARTNERS
export const hospitals: Partner[] = [
	{
		id: 'H001',
		name: 'Square Hospital Ltd.',
		type: 'HOSPITAL',
		category: 'LIFE',
		status: 'ACTIVE',
		email: 'contact@squarehospital.com',
		phone: '+880 1711-234567',
		address: '18/F Bir Uttam Qazi Nuruzzaman Sarak, Panthapath',
		location: 'Dhaka',
		tradeLicense: 'TL-DH-2024-001234',
		tinNumber: '123456789012',
		services: 24,
		rating: 4.8,
		discountEnabled: true,
		discountPercentage: 15,
		minDiscount: 10,
		maxDiscount: 25,
		discountType: 'SERVICE',
		cashlessEnabled: true,
		cashlessLimit: 50000000,
		autoApprovalThreshold: 10000000,
		preAuthRequired: true,
		authValidityDays: 30,
		requiredDocuments: ['National ID Card', 'Policy Certificate', 'Medical Prescription']
	},
	{
		id: 'H002',
		name: 'United Hospital Limited',
		type: 'HOSPITAL',
		category: 'LIFE',
		status: 'ACTIVE',
		email: 'info@uhlbd.com',
		phone: '+880 1711-345678',
		address: 'Plot 15, Road 71, Gulshan',
		location: 'Dhaka',
		tradeLicense: 'TL-DH-2024-001235',
		tinNumber: '123456789013',
		services: 32,
		rating: 4.9,
		discountEnabled: true,
		discountPercentage: 12,
		minDiscount: 8,
		maxDiscount: 20,
		discountType: 'SERVICE',
		cashlessEnabled: true,
		cashlessLimit: 75000000,
		autoApprovalThreshold: 15000000,
		preAuthRequired: true,
		authValidityDays: 30,
		requiredDocuments: ['National ID Card', 'Policy Certificate', 'Hospital Admission Form']
	},
	{
		id: 'H003',
		name: 'Apollo Hospitals Dhaka',
		type: 'HOSPITAL',
		category: 'LIFE',
		status: 'ACTIVE',
		email: 'contact@apollo-dhaka.com',
		phone: '+880 1711-456789',
		address: 'Plot 81, Block E, Bashundhara R/A',
		location: 'Dhaka',
		tradeLicense: 'TL-DH-2024-001236',
		tinNumber: '123456789014',
		services: 28,
		rating: 4.7,
		discountEnabled: true,
		discountPercentage: 10,
		minDiscount: 5,
		maxDiscount: 18,
		discountType: 'SERVICE',
		cashlessEnabled: true,
		cashlessLimit: 60000000,
		autoApprovalThreshold: 12000000,
		preAuthRequired: false,
		authValidityDays: 45,
		requiredDocuments: ['National ID Card', 'Policy Certificate']
	},
	{
		id: 'H004',
		name: 'Labaid Specialized Hospital',
		type: 'HOSPITAL',
		category: 'LIFE',
		status: 'ACTIVE',
		email: 'info@labaidgroup.com',
		phone: '+880 1711-567890',
		address: 'House 1, Road 4, Dhanmondi',
		location: 'Dhaka',
		tradeLicense: 'TL-DH-2024-001237',
		tinNumber: '123456789015',
		services: 18,
		rating: 4.6,
		discountEnabled: true,
		discountPercentage: 20,
		minDiscount: 15,
		maxDiscount: 30,
		discountType: 'SERVICE',
		cashlessEnabled: true,
		cashlessLimit: 40000000,
		autoApprovalThreshold: 8000000,
		preAuthRequired: true,
		authValidityDays: 30,
		requiredDocuments: ['National ID Card', 'Policy Certificate', 'Medical Prescription', 'Treatment Estimate']
	}
];

export const pharmacies: Partner[] = [
	{
		id: 'P001',
		name: 'Lazz Pharma Limited',
		type: 'PHARMACY',
		category: 'LIFE',
		status: 'ACTIVE',
		email: 'info@lazzpharma.com',
		phone: '+880 1711-678901',
		address: 'Ka-9, Pragati Sarani, Shahjadpur',
		location: 'Nationwide',
		tradeLicense: 'TL-DH-2024-002001',
		tinNumber: '223456789012',
		outlets: 45,
		rating: 4.5,
		discountEnabled: true,
		discountPercentage: 5,
		minDiscount: 3,
		maxDiscount: 10,
		discountType: 'MEDICATION',
		cashlessEnabled: true,
		cashlessLimit: 5000000,
		autoApprovalThreshold: 1000000,
		preAuthRequired: false,
		authValidityDays: 60,
		requiredDocuments: ['National ID Card', 'Policy Certificate']
	},
	{
		id: 'P002',
		name: 'Pharmacy Plus',
		type: 'PHARMACY',
		category: 'LIFE',
		status: 'ACTIVE',
		email: 'contact@pharmacyplus.com.bd',
		phone: '+880 1711-789012',
		address: 'Sonargaon Road, Hatirpool',
		location: 'Dhaka',
		tradeLicense: 'TL-DH-2024-002002',
		tinNumber: '223456789013',
		outlets: 12,
		rating: 4.6,
		discountEnabled: true,
		discountPercentage: 8,
		minDiscount: 5,
		maxDiscount: 12,
		discountType: 'MEDICATION',
		cashlessEnabled: true,
		cashlessLimit: 3000000,
		autoApprovalThreshold: 500000,
		preAuthRequired: false,
		authValidityDays: 45,
		requiredDocuments: ['National ID Card', 'Medical Prescription']
	},
	{
		id: 'P003',
		name: 'MedEasy Pharmacy',
		type: 'PHARMACY',
		category: 'LIFE',
		status: 'ACTIVE',
		email: 'support@medeasy.bd',
		phone: '+880 1711-890123',
		address: 'Green Road, Farmgate',
		location: 'Nationwide',
		tradeLicense: 'TL-DH-2024-002003',
		tinNumber: '223456789014',
		outlets: 28,
		rating: 4.4,
		discountEnabled: true,
		discountPercentage: 7,
		minDiscount: 4,
		maxDiscount: 10,
		discountType: 'MEDICATION',
		cashlessEnabled: false,
		cashlessLimit: 0,
		autoApprovalThreshold: 0,
		preAuthRequired: false,
		authValidityDays: 30,
		requiredDocuments: []
	},
	{
		id: 'P004',
		name: 'HealthMart',
		type: 'PHARMACY',
		category: 'LIFE',
		status: 'PENDING',
		email: 'info@healthmart.bd',
		phone: '+880 1711-901234',
		address: 'Station Road, Agrabad',
		location: 'Chittagong',
		tradeLicense: 'TL-CH-2024-002004',
		tinNumber: '223456789015',
		outlets: 8,
		rating: 4.3,
		discountEnabled: true,
		discountPercentage: 10,
		minDiscount: 8,
		maxDiscount: 15,
		discountType: 'MEDICATION',
		cashlessEnabled: true,
		cashlessLimit: 2000000,
		autoApprovalThreshold: 400000,
		preAuthRequired: false,
		authValidityDays: 30,
		requiredDocuments: ['National ID Card', 'Policy Certificate']
	}
];

export const doctors: Partner[] = [
	{
		id: 'D001',
		name: 'Dr. Ahmed Hassan',
		type: 'DOCTOR',
		category: 'LIFE',
		status: 'ACTIVE',
		email: 'dr.ahmed@squarehospital.com',
		phone: '+880 1711-012345',
		address: 'Square Hospital, Panthapath',
		location: 'Square Hospital',
		specialty: 'Cardiology',
		rating: 4.8,
		discountEnabled: true,
		discountPercentage: 15,
		minDiscount: 10,
		maxDiscount: 20,
		discountType: 'CONSULTATION',
		cashlessEnabled: true,
		cashlessLimit: 2000000,
		autoApprovalThreshold: 500000,
		preAuthRequired: false,
		authValidityDays: 15,
		requiredDocuments: ['National ID Card', 'Policy Certificate']
	},
	{
		id: 'D002',
		name: 'Dr. Fatima Khan',
		type: 'DOCTOR',
		category: 'LIFE',
		status: 'ACTIVE',
		email: 'dr.fatima@united.com',
		phone: '+880 1711-123456',
		address: 'United Hospital, Gulshan',
		location: 'United Hospital',
		specialty: 'Pediatrics',
		rating: 4.9,
		discountEnabled: true,
		discountPercentage: 12,
		minDiscount: 8,
		maxDiscount: 18,
		discountType: 'CONSULTATION',
		cashlessEnabled: true,
		cashlessLimit: 1500000,
		autoApprovalThreshold: 400000,
		preAuthRequired: false,
		authValidityDays: 20,
		requiredDocuments: ['National ID Card', 'Policy Certificate']
	},
	{
		id: 'D003',
		name: 'Dr. Rashid Ali',
		type: 'DOCTOR',
		category: 'LIFE',
		status: 'ACTIVE',
		email: 'dr.rashid@apollo.com',
		phone: '+880 1711-234567',
		address: 'Apollo Hospital, Bashundhara',
		location: 'Apollo Hospital',
		specialty: 'Orthopedics',
		rating: 4.7,
		discountEnabled: true,
		discountPercentage: 10,
		minDiscount: 5,
		maxDiscount: 15,
		discountType: 'CONSULTATION',
		cashlessEnabled: true,
		cashlessLimit: 1800000,
		autoApprovalThreshold: 450000,
		preAuthRequired: false,
		authValidityDays: 15,
		requiredDocuments: ['National ID Card', 'Policy Certificate']
	},
	{
		id: 'D004',
		name: 'Dr. Nadia Rahman',
		type: 'DOCTOR',
		category: 'LIFE',
		status: 'ACTIVE',
		email: 'dr.nadia@labaid.com',
		phone: '+880 1711-345678',
		address: 'Labaid Hospital, Dhanmondi',
		location: 'Labaid Hospital',
		specialty: 'Dermatology',
		rating: 4.6,
		discountEnabled: true,
		discountPercentage: 18,
		minDiscount: 15,
		maxDiscount: 25,
		discountType: 'CONSULTATION',
		cashlessEnabled: true,
		cashlessLimit: 1200000,
		autoApprovalThreshold: 300000,
		preAuthRequired: false,
		authValidityDays: 10,
		requiredDocuments: ['National ID Card', 'Policy Certificate']
	}
];

export const ambulances: Partner[] = [
	{
		id: 'A001',
		name: 'LifeLine Ambulance Service',
		type: 'AMBULANCE',
		category: 'LIFE',
		status: 'ACTIVE',
		email: 'emergency@lifeline.com.bd',
		phone: '+880 1711-456789',
		address: 'Mohakhali DOHS',
		location: 'Dhaka',
		serviceType: 'Advanced Life Support',
		vehicles: 8,
		rating: 4.7,
		discountEnabled: false,
		discountPercentage: 0,
		minDiscount: 0,
		maxDiscount: 0,
		discountType: 'SERVICE',
		cashlessEnabled: true,
		cashlessLimit: 5000000,
		autoApprovalThreshold: 2000000,
		preAuthRequired: false,
		authValidityDays: 1,
		requiredDocuments: ['Policy Certificate']
	},
	{
		id: 'A002',
		name: 'Medinova Emergency Services',
		type: 'AMBULANCE',
		category: 'LIFE',
		status: 'ACTIVE',
		email: 'contact@medinova.com.bd',
		phone: '+880 1711-567890',
		address: 'Uttara Sector 7',
		location: 'Dhaka',
		serviceType: 'Basic Life Support',
		vehicles: 5,
		rating: 4.5,
		discountEnabled: false,
		discountPercentage: 0,
		minDiscount: 0,
		maxDiscount: 0,
		discountType: 'SERVICE',
		cashlessEnabled: true,
		cashlessLimit: 3000000,
		autoApprovalThreshold: 1500000,
		preAuthRequired: false,
		authValidityDays: 1,
		requiredDocuments: ['Policy Certificate']
	},
	{
		id: 'A003',
		name: 'CityMed Ambulance',
		type: 'AMBULANCE',
		category: 'LIFE',
		status: 'ACTIVE',
		email: 'support@citymed.com.bd',
		phone: '+880 1811-678901',
		address: 'CDA Avenue, Agrabad',
		location: 'Chittagong',
		serviceType: 'Advanced Life Support',
		vehicles: 3,
		rating: 4.6,
		discountEnabled: false,
		discountPercentage: 0,
		minDiscount: 0,
		maxDiscount: 0,
		discountType: 'SERVICE',
		cashlessEnabled: true,
		cashlessLimit: 4000000,
		autoApprovalThreshold: 2000000,
		preAuthRequired: false,
		authValidityDays: 1,
		requiredDocuments: ['Policy Certificate']
	}
];

// NON-LIFE INSURANCE PARTNERS
export const autoRepairs: Partner[] = [
	{
		id: 'AR001',
		name: 'Auto Excellence',
		type: 'AUTO_REPAIR',
		category: 'NON_LIFE',
		status: 'ACTIVE',
		email: 'service@autoexcellence.bd',
		phone: '+880 1711-789012',
		address: 'Tejgaon Industrial Area',
		location: 'Dhaka',
		brands: 'All brands',
		rating: 4.5,
		discountEnabled: true,
		discountPercentage: 20,
		minDiscount: 15,
		maxDiscount: 30,
		discountType: 'SERVICE',
		cashlessEnabled: true,
		cashlessLimit: 20000000,
		autoApprovalThreshold: 5000000,
		preAuthRequired: true,
		authValidityDays: 7,
		requiredDocuments: ['National ID Card', 'Policy Certificate', 'Vehicle Registration']
	},
	{
		id: 'AR002',
		name: 'Car Care Center',
		type: 'AUTO_REPAIR',
		category: 'NON_LIFE',
		status: 'ACTIVE',
		email: 'info@carcare.bd',
		phone: '+880 1711-890123',
		address: 'Banani Road 11',
		location: 'Dhaka',
		brands: 'Toyota, Honda, Nissan',
		rating: 4.8,
		discountEnabled: true,
		discountPercentage: 15,
		minDiscount: 10,
		maxDiscount: 25,
		discountType: 'SERVICE',
		cashlessEnabled: true,
		cashlessLimit: 15000000,
		autoApprovalThreshold: 3000000,
		preAuthRequired: true,
		authValidityDays: 5,
		requiredDocuments: ['National ID Card', 'Policy Certificate', 'Vehicle Registration', 'Treatment Estimate']
	},
	{
		id: 'AR003',
		name: 'Premium Motors',
		type: 'AUTO_REPAIR',
		category: 'NON_LIFE',
		status: 'ACTIVE',
		email: 'service@premiummotors.bd',
		phone: '+880 1811-901234',
		address: 'Oxygen Road, Agrabad',
		location: 'Chittagong',
		brands: 'BMW, Mercedes, Audi',
		rating: 4.9,
		discountEnabled: true,
		discountPercentage: 25,
		minDiscount: 20,
		maxDiscount: 35,
		discountType: 'SERVICE',
		cashlessEnabled: true,
		cashlessLimit: 30000000,
		autoApprovalThreshold: 8000000,
		preAuthRequired: true,
		authValidityDays: 10,
		requiredDocuments: ['National ID Card', 'Policy Certificate', 'Vehicle Registration']
	},
	{
		id: 'AR004',
		name: 'Quick Fix Auto',
		type: 'AUTO_REPAIR',
		category: 'NON_LIFE',
		status: 'ACTIVE',
		email: 'contact@quickfixauto.bd',
		phone: '+880 1911-012345',
		address: 'Zindabazar',
		location: 'Sylhet',
		brands: 'All brands',
		rating: 4.3,
		discountEnabled: true,
		discountPercentage: 18,
		minDiscount: 12,
		maxDiscount: 28,
		discountType: 'SERVICE',
		cashlessEnabled: false,
		cashlessLimit: 0,
		autoApprovalThreshold: 0,
		preAuthRequired: false,
		authValidityDays: 0,
		requiredDocuments: []
	}
];

export const laptopRepairs: Partner[] = [
	{
		id: 'LR001',
		name: 'TechFix Solutions',
		type: 'LAPTOP_REPAIR',
		category: 'NON_LIFE',
		status: 'ACTIVE',
		email: 'support@techfix.bd',
		phone: '+880 1711-123456',
		address: 'Multiplan Center, New Elephantroad',
		location: 'Dhaka',
		brands: 'All brands',
		rating: 4.6,
		discountEnabled: true,
		discountPercentage: 15,
		minDiscount: 10,
		maxDiscount: 25,
		discountType: 'SERVICE',
		cashlessEnabled: true,
		cashlessLimit: 5000000,
		autoApprovalThreshold: 1000000,
		preAuthRequired: false,
		authValidityDays: 14,
		requiredDocuments: ['National ID Card', 'Policy Certificate']
	},
	{
		id: 'LR002',
		name: 'Laptop Care',
		type: 'LAPTOP_REPAIR',
		category: 'NON_LIFE',
		status: 'ACTIVE',
		email: 'info@laptopcare.bd',
		phone: '+880 1711-234567',
		address: 'IDB Bhaban, Agargaon',
		location: 'Dhaka',
		brands: 'Dell, HP, Lenovo',
		rating: 4.7,
		discountEnabled: true,
		discountPercentage: 12,
		minDiscount: 8,
		maxDiscount: 20,
		discountType: 'SERVICE',
		cashlessEnabled: true,
		cashlessLimit: 4000000,
		autoApprovalThreshold: 800000,
		preAuthRequired: false,
		authValidityDays: 10,
		requiredDocuments: ['National ID Card', 'Policy Certificate', 'Purchase Invoice']
	},
	{
		id: 'LR003',
		name: 'Computer Clinic',
		type: 'LAPTOP_REPAIR',
		category: 'NON_LIFE',
		status: 'ACTIVE',
		email: 'service@computerclinic.bd',
		phone: '+880 1811-345678',
		address: 'Kazir Dewri',
		location: 'Chittagong',
		brands: 'All brands',
		rating: 4.4,
		discountEnabled: true,
		discountPercentage: 18,
		minDiscount: 12,
		maxDiscount: 28,
		discountType: 'SERVICE',
		cashlessEnabled: false,
		cashlessLimit: 0,
		autoApprovalThreshold: 0,
		preAuthRequired: false,
		authValidityDays: 0,
		requiredDocuments: []
	},
	{
		id: 'LR004',
		name: 'Tech Support Pro',
		type: 'LAPTOP_REPAIR',
		category: 'NON_LIFE',
		status: 'PENDING',
		email: 'contact@techsupportpro.bd',
		phone: '+880 1711-456789',
		address: 'Banani DOHS',
		location: 'Dhaka',
		brands: 'Apple, Dell, ASUS',
		rating: 4.2,
		discountEnabled: true,
		discountPercentage: 10,
		minDiscount: 5,
		maxDiscount: 18,
		discountType: 'SERVICE',
		cashlessEnabled: true,
		cashlessLimit: 3000000,
		autoApprovalThreshold: 600000,
		preAuthRequired: false,
		authValidityDays: 7,
		requiredDocuments: ['National ID Card', 'Policy Certificate']
	}
];

export const mobileRepairs: Partner[] = [
	{
		id: 'MR001',
		name: 'Mobile Fix Center',
		type: 'MOBILE_REPAIR',
		category: 'NON_LIFE',
		status: 'ACTIVE',
		email: 'support@mobilefix.bd',
		phone: '+880 1711-567890',
		address: 'Bashundhara City Shopping Mall',
		location: 'Dhaka',
		brands: 'All brands',
		rating: 4.5,
		discountEnabled: true,
		discountPercentage: 10,
		minDiscount: 5,
		maxDiscount: 20,
		discountType: 'SERVICE',
		cashlessEnabled: true,
		cashlessLimit: 2000000,
		autoApprovalThreshold: 500000,
		preAuthRequired: false,
		authValidityDays: 7,
		requiredDocuments: ['National ID Card', 'Policy Certificate']
	},
	{
		id: 'MR002',
		name: 'Phone Care Plus',
		type: 'MOBILE_REPAIR',
		category: 'NON_LIFE',
		status: 'ACTIVE',
		email: 'info@phonecareplus.bd',
		phone: '+880 1711-678901',
		address: 'Jamuna Future Park',
		location: 'Dhaka',
		brands: 'Samsung, Apple, Xiaomi',
		rating: 4.8,
		discountEnabled: true,
		discountPercentage: 12,
		minDiscount: 8,
		maxDiscount: 18,
		discountType: 'SERVICE',
		cashlessEnabled: true,
		cashlessLimit: 2500000,
		autoApprovalThreshold: 600000,
		preAuthRequired: false,
		authValidityDays: 10,
		requiredDocuments: ['National ID Card', 'Policy Certificate', 'Purchase Receipt']
	},
	{
		id: 'MR003',
		name: 'Smart Repair Shop',
		type: 'MOBILE_REPAIR',
		category: 'NON_LIFE',
		status: 'ACTIVE',
		email: 'service@smartrepair.bd',
		phone: '+880 1811-789012',
		address: 'Agrabad Commercial Area',
		location: 'Chittagong',
		brands: 'All brands',
		rating: 4.6,
		discountEnabled: true,
		discountPercentage: 15,
		minDiscount: 10,
		maxDiscount: 25,
		discountType: 'SERVICE',
		cashlessEnabled: true,
		cashlessLimit: 1800000,
		autoApprovalThreshold: 400000,
		preAuthRequired: false,
		authValidityDays: 5,
		requiredDocuments: ['National ID Card', 'Policy Certificate']
	},
	{
		id: 'MR004',
		name: 'QuickFix Mobile',
		type: 'MOBILE_REPAIR',
		category: 'NON_LIFE',
		status: 'ACTIVE',
		email: 'contact@quickfixmobile.bd',
		phone: '+880 1911-890123',
		address: 'Uposhohor',
		location: 'Sylhet',
		brands: 'All brands',
		rating: 4.3,
		discountEnabled: true,
		discountPercentage: 8,
		minDiscount: 5,
		maxDiscount: 15,
		discountType: 'SERVICE',
		cashlessEnabled: false,
		cashlessLimit: 0,
		autoApprovalThreshold: 0,
		preAuthRequired: false,
		authValidityDays: 0,
		requiredDocuments: []
	}
];

// Combine all partners
export const allPartners: Partner[] = [
	...hospitals,
	...pharmacies,
	...doctors,
	...ambulances,
	...autoRepairs,
	...laptopRepairs,
	...mobileRepairs
];

// Helper functions
export function getPartnerById(id: string): Partner | undefined {
	return allPartners.find(p => p.id === id);
}

export function getLifePartners(): Partner[] {
	return allPartners.filter(p => p.category === 'LIFE');
}

export function getNonLifePartners(): Partner[] {
	return allPartners.filter(p => p.category === 'NON_LIFE');
}

export function getPartnersByType(type: Partner['type']): Partner[] {
	return allPartners.filter(p => p.type === type);
}
