# Unified Proto Generation Script for InsureTech (Windows)
# Verifies tools, loads BUF_TOKEN, then delegates to inject_gorm_tags.go
param(
    [switch]$SkipRegistry = $false,
    [switch]$Verbose = $false
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Split-Path -Parent $ScriptDir

Write-Host "===========================================" -ForegroundColor Cyan
Write-Host "InsureTech Proto Generation" -ForegroundColor Cyan
Write-Host "===========================================" -ForegroundColor Cyan
Write-Host "OS: Windows, PowerShell: $($PSVersionTable.PSVersion)" -ForegroundColor Gray
Write-Host ""

# Step 1: Verify tools
Write-Host "[1/2] Verifying tools..." -ForegroundColor Yellow
$requiredTools = @(
    @{ Name = "buf"; Install = "go install github.com/bufbuild/buf/cmd/buf@latest" },
    @{ Name = "protoc-gen-go"; Install = "go install google.golang.org/protobuf/cmd/protoc-gen-go@latest" }
)

foreach ($tool in $requiredTools) {
    $cmd = Get-Command $tool.Name -ErrorAction SilentlyContinue
    if (-not $cmd) {
        Write-Host "  Installing $($tool.Name)..." -ForegroundColor Yellow
        Invoke-Expression $tool.Install
        if ($LASTEXITCODE -ne 0) {
            Write-Host "  ERROR: Failed to install $($tool.Name)" -ForegroundColor Red
            exit 1
        }
    }
    else {
        Write-Host "  OK: $($tool.Name)" -ForegroundColor Green
    }
}

# Load BUF_TOKEN from .env if it exists
$envFile = Join-Path $RepoRoot ".env"
if (Test-Path $envFile) {
    $bufToken = Get-Content $envFile | Where-Object { $_ -match "^BUF_TOKEN=" } | ForEach-Object { $_ -replace "^BUF_TOKEN=", "" }
    $bufToken = $bufToken.Trim().Trim('"').Trim("'")
    if ($bufToken -and $bufToken -ne "") {
        $env:BUF_TOKEN = $bufToken
        Write-Host "  Loaded BUF_TOKEN from .env" -ForegroundColor Gray
    }
}

# Step 2: Run unified Go script (buf generate + GORM injection + registry)
Write-Host ""
Write-Host "[2/2] Running generation pipeline..." -ForegroundColor Yellow

Push-Location $RepoRoot
try {
    $goArgs = @("run", ".\scripts\inject_gorm_tags.go", "--generate")
    if (-not $SkipRegistry) { $goArgs += "--registry" }
    if ($Verbose) { $goArgs += "--verbose" }
    & go @goArgs
    if ($LASTEXITCODE -ne 0) {
        Write-Host "  ERROR: Generation pipeline failed" -ForegroundColor Red
        exit 1
    }
}
finally {
    Pop-Location
}

Write-Host ""
Write-Host "===========================================" -ForegroundColor Cyan
Write-Host "Proto generation complete!" -ForegroundColor Green
Write-Host "===========================================" -ForegroundColor Cyan

# Step 3: Sync generated TypeScript protos into b2b portal local lib
$tsSourceDir = Join-Path $RepoRoot "gen\ts\insuretech"
$portalProtoRoot = Join-Path $RepoRoot "b2b_portal\src\lib\proto-generated"

if (Test-Path $tsSourceDir) {
    New-Item -ItemType Directory -Path $portalProtoRoot -Force | Out-Null
    Copy-Item -Recurse -Force $tsSourceDir $portalProtoRoot
    Write-Host "Synced TypeScript protos to b2b_portal/src/lib/proto-generated/insuretech" -ForegroundColor Green
}
else {
    Write-Host "WARNING: TS proto source not found at gen/ts/insuretech; skipped portal proto sync" -ForegroundColor Yellow
}

# Ensure google/api compatibility shims are present.
# These are NOT generated by buf (google.api.* descriptors are not needed at runtime),
# but every service _pb.ts that uses google.api.http or google.api.field_behavior imports them.
# If the shim file is missing after a fresh sync, the portal TypeScript build will fail.
$googleApiDir = Join-Path $portalProtoRoot "google\api"
New-Item -ItemType Directory -Path $googleApiDir -Force | Out-Null

$shims = @{
    "annotations_pb.ts"   = @"
// Local compatibility shim for generated proto imports in b2b_portal.
// The portal currently consumes message types only and does not require
// google.api HTTP annotation descriptors at runtime.
import type { GenFile } from "@bufbuild/protobuf/codegenv1";

export const file_google_api_annotations = {} as GenFile;
"@
    "field_behavior_pb.ts" = @"
// Local compatibility shim for generated proto imports in b2b_portal.
// The portal currently consumes message types only and does not require
// google.api field behavior descriptors at runtime.
import type { GenFile } from "@bufbuild/protobuf/codegenv1";

export const file_google_api_field_behavior = {} as GenFile;
"@
}

foreach ($shimFile in $shims.Keys) {
    $shimPath = Join-Path $googleApiDir $shimFile
    if (-not (Test-Path $shimPath)) {
        # Write with LF line endings (required for Linux Docker builds)
        $shimContent = $shims[$shimFile] -replace "`r`n", "`n"
        [System.IO.File]::WriteAllText($shimPath, $shimContent, [System.Text.UTF8Encoding]::new($false))
        Write-Host "Created google/api shim: $shimFile" -ForegroundColor Yellow
    }
    else {
        Write-Host "OK: google/api shim exists: $shimFile" -ForegroundColor Green
    }
}

