#!/bin/bash
# Unified Proto Generation Script for InsureTech (Linux/Mac)
# Verifies tools, loads BUF_TOKEN, then delegates to inject_gorm_tags.go

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VERBOSE=false
SKIP_REGISTRY=false

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --skip-registry) SKIP_REGISTRY=true ;;
        --verbose) VERBOSE=true ;;
        *) echo "Unknown parameter: $1"; exit 1 ;;
    esac
    shift
done

echo "==========================================="
echo "InsureTech Proto Generation"
echo "==========================================="
echo "OS: $(uname -s), Arch: $(uname -m)"
echo ""

# Step 1: Verify tools (auto-install if missing)
echo "[1/2] Verifying tools..."
BOOTSTRAP_SCRIPT="$SCRIPT_DIR/bootstrap.sh"
if [ -f "$BOOTSTRAP_SCRIPT" ]; then
    bash "$BOOTSTRAP_SCRIPT" --go-only
else
    # Fallback: inline check for minimum tools
    check_tool() {
        if ! command -v "$1" &>/dev/null; then
            echo "  Installing $1..."
            go install "$2"
        else
            echo "  OK: $1"
        fi
    }
    check_tool "buf"           "github.com/bufbuild/buf/cmd/buf@latest"
    check_tool "protoc-gen-go" "google.golang.org/protobuf/cmd/protoc-gen-go@latest"
fi

# Ensure GOPATH/bin is in PATH before the Go generator invokes external tools.
if command -v go &>/dev/null; then
    export PATH="$(go env GOPATH)/bin:$PATH"
fi

# Load BUF_TOKEN from .env if it exists
if [ -f "$REPO_ROOT/.env" ]; then
    BUF_TOKEN=$(grep '^BUF_TOKEN=' "$REPO_ROOT/.env" 2>/dev/null | sed 's/^BUF_TOKEN=//' | tr -d '"' | tr -d "'" | xargs)
    if [ -n "$BUF_TOKEN" ]; then
        export BUF_TOKEN
        echo "  Loaded BUF_TOKEN from .env"
    fi
fi

# Step 2: Run unified Go script (buf generate + GORM injection + registry)
echo ""
echo "[2/2] Running generation pipeline..."

# Check that go is available
if ! command -v go &>/dev/null; then
    echo "  ERROR: 'go' command not found. Please ensure Go is installed and in PATH." >&2
    exit 1
fi

cd "$REPO_ROOT"
GO_ARGS=("--generate")
if [ "$SKIP_REGISTRY" = false ]; then
    GO_ARGS+=("--registry")
fi
if [ "$VERBOSE" = true ]; then
    GO_ARGS+=("--verbose")
fi
go run ./scripts/inject_gorm_tags.go "${GO_ARGS[@]}"

echo ""
echo "==========================================="
echo "Proto generation complete!"
echo "==========================================="

# Step 3: Sync generated TypeScript protos into b2b portal local lib
TS_SRC="$REPO_ROOT/gen/ts/insuretech"
PORTAL_PROTO="$REPO_ROOT/b2b_portal/src/lib/proto-generated"

if [ -d "$TS_SRC" ]; then
    mkdir -p "$PORTAL_PROTO"
    cp -r "$TS_SRC" "$PORTAL_PROTO/"
    echo "Synced TypeScript protos to b2b_portal/src/lib/proto-generated/insuretech"
else
    echo "WARNING: TS proto source not found at gen/ts/insuretech; skipped portal proto sync"
fi

# Ensure google/api compatibility shims are present.
# These are NOT generated by buf (google.api.* descriptors are not needed at runtime),
# but every service _pb.ts that uses google.api.http or google.api.field_behavior imports them.
# If the shim file is missing after a fresh sync, the portal TypeScript build will fail.
GOOGLE_API_DIR="$PORTAL_PROTO/google/api"
mkdir -p "$GOOGLE_API_DIR"

# Create annotations_pb.ts shim
if [ ! -f "$GOOGLE_API_DIR/annotations_pb.ts" ]; then
    cat > "$GOOGLE_API_DIR/annotations_pb.ts" << 'EOF'
// Local compatibility shim for generated proto imports in b2b_portal.
// The portal currently consumes message types only and does not require
// google.api HTTP annotation descriptors at runtime.
import type { GenFile } from "@bufbuild/protobuf/codegenv1";

export const file_google_api_annotations = {} as GenFile;
EOF
    echo "Created google/api shim: annotations_pb.ts"
else
    echo "OK: google/api shim exists: annotations_pb.ts"
fi

# Create field_behavior_pb.ts shim
if [ ! -f "$GOOGLE_API_DIR/field_behavior_pb.ts" ]; then
    cat > "$GOOGLE_API_DIR/field_behavior_pb.ts" << 'EOF'
// Local compatibility shim for generated proto imports in b2b_portal.
// The portal currently consumes message types only and does not require
// google.api field behavior descriptors at runtime.
import type { GenFile } from "@bufbuild/protobuf/codegenv1";

export const file_google_api_field_behavior = {} as GenFile;
EOF
    echo "Created google/api shim: field_behavior_pb.ts"
else
    echo "OK: google/api shim exists: field_behavior_pb.ts"
fi
