// <auto-generated />
using System;
using InsuranceEngine.Policy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InsuranceEngine.Policy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PolicyDbContext))]
    [Migration("20260322162718_InitialUnified")]
    partial class InitialUnified
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("insurance_schema")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("endorsement_number_seq", "insurance_schema");

            modelBuilder.HasSequence("policy_number_seq", "insurance_schema");

            modelBuilder.Entity("InsuranceEngine.Policy.Domain.Entities.Endorsement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuditInfoJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("audit_info");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndorsementNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PremiumAdjustmentAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("premium_adjustment_amount");

                    b.Property<string>("PremiumAdjustmentCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("BDT")
                        .HasColumnName("premium_adjustment_currency");

                    b.Property<bool>("PremiumRefundRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EndorsementNumber")
                        .IsUnique();

                    b.HasIndex("PolicyId");

                    b.HasIndex("Status");

                    b.ToTable("endorsements", "insurance_schema");
                });

            modelBuilder.Entity("InsuranceEngine.Policy.Domain.Entities.Nominee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BeneficiaryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NidNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nid_number");

                    b.Property<string>("NomineeDobText")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nominee_dob_text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("SharePercentage")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("NidNumber");

                    b.HasIndex("PolicyId");

                    b.ToTable("policy_nominees", "insurance_schema");
                });

            modelBuilder.Entity("InsuranceEngine.Policy.Domain.Entities.PolicyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClaimsHistorySummary")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EnrollmentEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EnrollmentStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasExistingPolicies")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OccupationRiskClass")
                        .HasColumnType("text");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentFrequency")
                        .HasColumnType("text");

                    b.Property<string>("PaymentGatewayReference")
                        .HasColumnType("text");

                    b.Property<string>("PolicyDocumentUrl")
                        .HasColumnType("text");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("PremiumAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("premium_amount");

                    b.Property<string>("PremiumCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("BDT")
                        .HasColumnName("premium_currency");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProposerDetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("proposer_details");

                    b.Property<string>("ProviderName")
                        .HasColumnType("text");

                    b.Property<Guid?>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("text");

                    b.Property<long>("ServiceFeeAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("service_fee_amount");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("SumInsuredAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("sum_insured_amount");

                    b.Property<string>("SumInsuredCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("BDT")
                        .HasColumnName("sum_insured_currency");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("integer");

                    b.Property<long>("TotalPayableAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_payable_amount");

                    b.Property<string>("UnderwritingData")
                        .HasColumnType("jsonb")
                        .HasColumnName("underwriting_data");

                    b.Property<Guid?>("UnderwritingDecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("VatTaxAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("vat_tax_amount");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.HasIndex("Status");

                    b.ToTable("policies", "insurance_schema");
                });

            modelBuilder.Entity("InsuranceEngine.Policy.Domain.Entities.PolicyRider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CoverageAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("coverage_amount");

                    b.Property<string>("CoverageCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("BDT")
                        .HasColumnName("coverage_currency");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<long>("PremiumAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("premium_amount");

                    b.Property<string>("PremiumCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("BDT")
                        .HasColumnName("premium_currency");

                    b.Property<string>("RiderName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.ToTable("policy_riders", "insurance_schema");
                });

            modelBuilder.Entity("InsuranceEngine.SharedKernel.Domain.Entities.Beneficiary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuditInfo")
                        .HasColumnType("jsonb");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("KycCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferralCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReferredBy")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskScore")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("beneficiaries", "insurance_schema");
                });

            modelBuilder.Entity("InsuranceEngine.SharedKernel.Domain.Entities.BusinessBeneficiary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActivePoliciesCount")
                        .HasColumnType("integer");

                    b.Property<string>("AuditInfo")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uuid");

                    b.Property<string>("BinNumber")
                        .HasColumnType("text");

                    b.Property<string>("BusinessAddressJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessNameBn")
                        .HasColumnType("text");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactInfoJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("integer");

                    b.Property<string>("FocalPersonContact")
                        .HasColumnType("text");

                    b.Property<string>("FocalPersonContactJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("FocalPersonDesignation")
                        .HasColumnType("text");

                    b.Property<string>("FocalPersonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FocalPersonNid")
                        .HasColumnType("text");

                    b.Property<DateTime?>("IncorporationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Industry")
                        .HasColumnType("text");

                    b.Property<string>("IndustrySector")
                        .HasColumnType("text");

                    b.Property<int>("PendingActionsCount")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryContactJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("RegisteredAddressJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.Property<string>("TaxId")
                        .HasColumnType("text");

                    b.Property<string>("TinNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalEmployeesCovered")
                        .HasColumnType("integer");

                    b.Property<long>("TotalPremiumAmount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TradeLicenseExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TradeLicenseIssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TradeLicenseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId")
                        .IsUnique();

                    b.ToTable("business_beneficiaries", "insurance_schema");
                });

            modelBuilder.Entity("InsuranceEngine.SharedKernel.Domain.Entities.IndividualBeneficiary", b =>
                {
                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuditInfo")
                        .HasColumnType("jsonb");

                    b.Property<string>("BirthCertificateNumber")
                        .HasColumnType("text");

                    b.Property<string>("ContactInfoJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FatherName")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullNameBn")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("numeric");

                    b.Property<string>("MotherName")
                        .HasColumnType("text");

                    b.Property<string>("NidNumber")
                        .HasColumnType("text");

                    b.Property<string>("NomineeName")
                        .HasColumnType("text");

                    b.Property<string>("NomineeRelationship")
                        .HasColumnType("text");

                    b.Property<string>("Occupation")
                        .HasColumnType("text");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("text");

                    b.Property<string>("PermanentAddressJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("PresentAddressJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("TinNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BeneficiaryId");

                    b.ToTable("individual_beneficiaries", "insurance_schema");
                });

            modelBuilder.Entity("InsuranceEngine.Policy.Domain.Entities.Nominee", b =>
                {
                    b.HasOne("InsuranceEngine.SharedKernel.Domain.Entities.Beneficiary", "Beneficiary")
                        .WithMany()
                        .HasForeignKey("BeneficiaryId");

                    b.HasOne("InsuranceEngine.Policy.Domain.Entities.PolicyEntity", null)
                        .WithMany("Nominees")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");
                });

            modelBuilder.Entity("InsuranceEngine.Policy.Domain.Entities.PolicyRider", b =>
                {
                    b.HasOne("InsuranceEngine.Policy.Domain.Entities.PolicyEntity", null)
                        .WithMany("Riders")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InsuranceEngine.SharedKernel.Domain.Entities.BusinessBeneficiary", b =>
                {
                    b.HasOne("InsuranceEngine.SharedKernel.Domain.Entities.Beneficiary", "Beneficiary")
                        .WithOne("BusinessDetails")
                        .HasForeignKey("InsuranceEngine.SharedKernel.Domain.Entities.BusinessBeneficiary", "BeneficiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");
                });

            modelBuilder.Entity("InsuranceEngine.SharedKernel.Domain.Entities.IndividualBeneficiary", b =>
                {
                    b.HasOne("InsuranceEngine.SharedKernel.Domain.Entities.Beneficiary", "Beneficiary")
                        .WithOne("IndividualDetails")
                        .HasForeignKey("InsuranceEngine.SharedKernel.Domain.Entities.IndividualBeneficiary", "BeneficiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");
                });

            modelBuilder.Entity("InsuranceEngine.Policy.Domain.Entities.PolicyEntity", b =>
                {
                    b.Navigation("Nominees");

                    b.Navigation("Riders");
                });

            modelBuilder.Entity("InsuranceEngine.SharedKernel.Domain.Entities.Beneficiary", b =>
                {
                    b.Navigation("BusinessDetails");

                    b.Navigation("IndividualDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
