// Auto-generated SDK Entry Point — DO NOT EDIT
// Generated by InsureTech API Pipeline

// ─── Core ApiResponse<T> envelope + type guards ───────────────────────────────
export type {
  ApiResponse,
  ResponseMeta,
  PaginationMeta,
  PaginationRequest,
  Money,
  Address,
  Timestamp,
  DateString,
  UUID,
} from './types';
export { unwrapData, isApiSuccess, isApiError } from './types';

// ─── Structured error classes ─────────────────────────────────────────────────
export { InsureTechApiError, ApiError } from './errors';
export type { ApiErrorDetail, FieldViolation } from './errors';

// ─── Generated services and types (hey-api) ───────────────────────────────────
export * from './sdk.gen';
export * from './types.gen';

// ─── Custom client helper ─────────────────────────────────────────────────────
export { createInsureTechClient } from './client-wrapper';
export type { InsureTechClientConfig } from './client-wrapper';
