// Auto-generated — DO NOT EDIT
// Generated by InsureTech API Pipeline

import type { ApiErrorDetail } from './errors'

// ─── Core API Envelope ────────────────────────────────────────────────────────

/**
 * Unified API response envelope — identical shape for ALL endpoints.
 * success:true  → data has payload, error is null
 * success:false → data is null, error has details
 */
export interface ApiResponse<T> {
  success: boolean
  data: T | null
  error: ApiErrorDetail | null
  meta: ResponseMeta
}

export interface ResponseMeta {
  request_id: string
  timestamp: string
  pagination?: PaginationMeta | null
}

export interface PaginationMeta {
  page: number
  page_size: number
  total_count: number
  total_pages: number
  has_next: boolean
  has_prev: boolean
}

// ─── Domain Base Types ────────────────────────────────────────────────────────

export interface PaginationRequest {
  page?: number
  page_size?: number
  sort_by?: string
  sort_order?: 'asc' | 'desc'
  search?: string
  from_date?: string
  to_date?: string
}

export interface Money {
  amount: string
  currency: string
}

export interface Address {
  line1: string
  line2?: string
  city: string
  state?: string
  postal_code: string
  country: string
}

export type Timestamp = string
export type DateString = string
export type UUID = string

/**
 * unwrapData — safely unwraps the data field from an ApiResponse.
 * Returns data on success, throws InsureTechApiError on failure.
 */
export function unwrapData<T>(response: ApiResponse<T>): T {
  if (!response.success || response.data === null || response.data === undefined) {
    const { InsureTechApiError } = require('./errors')
    throw new InsureTechApiError(response.error ?? {
      code: 'UNKNOWN_ERROR',
      message: 'API returned success:false with no error details',
      error_id: response.meta?.request_id ?? '',
      http_status_code: 500,
      retryable: false,
      field_violations: [],
    })
  }
  return response.data
}

/**
 * isApiSuccess — type guard, narrows ApiResponse<T> to success case.
 */
export function isApiSuccess<T>(r: ApiResponse<T>): r is ApiResponse<T> & { success: true; data: T; error: null } {
  return r.success === true && r.data !== null
}

/**
 * isApiError — type guard, narrows ApiResponse<T> to error case.
 */
export function isApiError<T>(r: ApiResponse<T>): r is ApiResponse<T> & { success: false; data: null; error: ApiErrorDetail } {
  return r.success === false
}
