PricingConfig:
  type: object
  properties:
    pricing_config_id:
      type: string
      description: '@inject_tag: gorm:"primaryKey;column:pricing_config_id;not null"'
    product_id:
      type: string
      description: '@inject_tag: gorm:"column:product_id;not null"'
    rules:
      type: array
      items:
        $ref: '#/components/schemas/PricingRule'
        description: '@inject_tag: gorm:"column:rules;not null;serializer:proto_enum"'
      description: '@inject_tag: gorm:"column:rules;not null;serializer:proto_enum"'
    effective_from:
      type: string
      format: date-time
      description: "@inject_tag: gorm:\"column:effective_from;not null;serializer:proto_timestamp\"\
        \n null;serializer:proto_timestamp\""
    effective_to:
      type: string
      format: date-time
      description: '@inject_tag: gorm:"column:effective_to;serializer:proto_timestamp"'
    created_at:
      type: string
      format: date-time
      description: '@inject_tag: gorm:"column:created_at;not null;serializer:proto_timestamp"'
    updated_at:
      type: string
      format: date-time
      description: '@inject_tag: gorm:"column:updated_at;not null;serializer:proto_timestamp"'
  description: "Product pricing configuration\n Maps to 'pricing_configs' table in\
    \ product_schema"
